name = "openlen-status"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = false

routes = [
  { pattern = "status.openlen.com/*", zone_name = "openlen.com" }
]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "openlen-status"
database_id = "31a195a1-d7bd-4cda-8bb3-2bd5a4afff04"

[vars]
CANARY_HOST = "headwaters-demo.openlen.com"
ALERT_FROM = "OpenLen Status <alerts@openlen.com>"
