import { FilesystemStorage } from "./filesystem";
import { R2Storage } from "./r2";
import type { StorageAdapter } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// "Imagenes by OpenLen" storage adapter.
//
// The curated hero-image library (3D abstracts + claymorph + fashion editorial)
// lives in its own R2 bucket — same rationale as templates: a globally
// cacheable, read-by-every-gallery-visitor asset set deserves its own cache
// policy and public domain, separate from one-off user uploads.
//
// Falls back to the local filesystem (`./public/openlen-images/`) when R2_*
// env vars aren't set, so `npm run openlen-images:process` and local dev keep
// working without a Cloudflare account. The WebP variants are generated by
// scripts/openlen-images/process.ts and uploaded through this adapter; the
// manifest.json it emits records whatever URLs the adapter returns.
// ─────────────────────────────────────────────────────────────────────────────

let cached: StorageAdapter | null = null;

export function getOpenLenImageStorage(): StorageAdapter {
  if (cached) return cached;
  cached = buildStorage();
  return cached;
}

function buildStorage(): StorageAdapter {
  const {
    R2_ACCOUNT_ID,
    R2_ACCESS_KEY,
    R2_SECRET_KEY,
    R2_IMAGES_BUCKET,
    R2_IMAGES_PUBLIC_URL,
    OPENLEN_IMAGES_DIR,
    OPENLEN_IMAGES_PUBLIC_URL,
  } = process.env;

  if (R2_ACCOUNT_ID && R2_ACCESS_KEY && R2_SECRET_KEY) {
    return new R2Storage({
      accountId: R2_ACCOUNT_ID,
      accessKey: R2_ACCESS_KEY,
      secretKey: R2_SECRET_KEY,
      bucket: R2_IMAGES_BUCKET || "openlen-images",
      publicUrlBase: R2_IMAGES_PUBLIC_URL || "https://images.openlen.com",
    });
  }

  return new FilesystemStorage({
    rootDir: OPENLEN_IMAGES_DIR || "./public/openlen-images",
    publicUrlBase: OPENLEN_IMAGES_PUBLIC_URL || "/openlen-images",
  });
}

export function __setOpenLenImageStorageForTest(
  adapter: StorageAdapter | null,
): void {
  cached = adapter;
}
