import type { ReactNode } from "react";
import { FileCode, Zap } from "lucide-react";
import { ThumbAcme, ThumbBloom, ThumbLumen } from "./thumbnails";

interface DemoCard {
  node: ReactNode;
  name: string;
  seconds: number;
  prompt: string;
}

const cards: DemoCard[] = [
  {
    node: <ThumbLumen />,
    name: "lumen.ai",
    seconds: 42,
    prompt: "A landing page for a real-time analytics tool with AI morning summaries.",
  },
  {
    node: <ThumbBloom />,
    name: "bloom.skincare",
    seconds: 47,
    prompt:
      "An e-commerce homepage for a small-batch botanical skincare brand from Oslo.",
  },
  {
    node: <ThumbAcme />,
    name: "acme.cloud",
    seconds: 38,
    prompt: "A developer-tool landing page for one-command serverless deployment.",
  },
];

export function DemoStrip() {
  return (
    <section className="relative border-y border-zinc-200 dark:border-zinc-800 bg-zinc-50/60 dark:bg-zinc-950">
      <div className="mx-auto max-w-6xl px-6 py-20">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-10">
          <div>
            <div className="inline-flex items-center gap-2 text-xs font-medium text-coral-700 dark:text-coral-400 mb-2">
              <span className="relative flex h-1.5 w-1.5">
                <span className="absolute inline-flex h-full w-full rounded-full bg-coral-500 opacity-75 animate-ping" />
                <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-coral-500" />
              </span>
              LIVE — generated today
            </div>
            <h2 className="text-3xl sm:text-4xl font-semibold tracking-tight">
              Real prompts.
              <br className="sm:hidden" />
              <span className="text-zinc-500 dark:text-zinc-500"> Real pages.</span>
            </h2>
          </div>
          <div className="text-sm text-zinc-500 dark:text-zinc-500 max-w-xs">
            Every page below was generated by Inari this morning. Type a prompt, get a
            page. No design taste required.
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {cards.map((t, i) => (
            <article key={i} className="group">
              <div className="relative">
                <div className="absolute -top-2.5 left-3 z-10 inline-flex items-center gap-1.5 rounded-full bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 px-2.5 py-1 text-[11px] font-medium shadow-md">
                  <Zap size={11} className="text-coral-400 dark:text-coral-500" />
                  Generated in {t.seconds}s
                </div>
                <div className="aspect-[4/3] [&>div]:h-full [&>div]:w-full transition duration-300 group-hover:-translate-y-1">
                  {t.node}
                </div>
              </div>
              <div className="mt-3 flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-sm font-medium truncate">{t.name}</div>
                  <div className="text-xs text-zinc-500 dark:text-zinc-500 truncate">
                    &ldquo;{t.prompt}&rdquo;
                  </div>
                </div>
                <button
                  type="button"
                  className="shrink-0 inline-flex items-center gap-1 rounded-md text-[11px] text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100 transition"
                >
                  <FileCode size={12} /> View code
                </button>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
