import { ArrowRight, Star } from "lucide-react";
import { GithubIcon } from "@/components/ui/brand-icons";
import { HeroPromptInput } from "./hero-prompt-input";
import { ThumbAcme, ThumbBloom, ThumbDrift } from "./thumbnails";

const avatarColors = ["#FF5A36", "#22d3ee", "#a78bfa", "#facc15", "#34d399"];

export function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div className="absolute inset-0 grid-bg opacity-60" aria-hidden />
      <div className="absolute inset-x-0 top-0 h-[640px] hero-glow" aria-hidden />
      <div
        className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-coral-500/60 to-transparent"
        aria-hidden
      />

      <div className="relative mx-auto max-w-6xl px-6 pt-20 pb-24 sm:pt-28 sm:pb-32">
        <div className="flex flex-col items-center text-center">
          <a
            href="#changelog"
            className="group inline-flex items-center gap-2 rounded-full bg-white dark:bg-zinc-950 ring-1 ring-zinc-200 dark:ring-zinc-800 px-3 py-1 text-xs font-medium text-zinc-700 dark:text-zinc-300 shadow-sm hover:ring-zinc-300 dark:hover:ring-zinc-700 transition"
          >
            <span className="inline-flex items-center gap-1 rounded-full bg-coral-500/10 text-coral-700 dark:text-coral-300 px-2 py-0.5 text-[10px] font-semibold tracking-wide uppercase">
              New
            </span>
            v0.4 — FLUX.2 HD image generation
            <ArrowRight
              size={12}
              className="opacity-50 transition group-hover:translate-x-0.5 group-hover:opacity-100"
            />
          </a>

          <h1 className="mt-7 max-w-4xl text-balance text-5xl sm:text-6xl md:text-7xl font-semibold tracking-tightest leading-[1.02]">
            Beautiful landing pages.
            <br />
            <span className="text-zinc-500 dark:text-zinc-500">AI-built.</span>{" "}
            <span className="bg-gradient-to-br from-coral-500 to-coral-700 bg-clip-text text-transparent">
              Open source.
            </span>
          </h1>

          <p className="mt-6 max-w-xl text-pretty text-lg text-zinc-600 dark:text-zinc-400">
            Lovable quality.{" "}
            <span className="text-zinc-900 dark:text-zinc-100 font-medium">
              Your code.
            </span>{" "}
            <span className="whitespace-nowrap text-zinc-900 dark:text-zinc-100 font-medium">
              $19 / month.
            </span>
          </p>

          <div className="mt-10 w-full max-w-2xl">
            <HeroPromptInput />
          </div>

          <div className="mt-5 flex flex-wrap items-center justify-center gap-x-4 gap-y-2 text-xs text-zinc-500 dark:text-zinc-500">
            <div className="flex items-center gap-2">
              <div className="flex -space-x-1.5">
                {avatarColors.map((c, i) => (
                  <span
                    key={i}
                    className="h-5 w-5 rounded-full ring-2 ring-white dark:ring-[#0a0a0a]"
                    style={{ background: c }}
                  />
                ))}
              </div>
              <span>
                <span className="font-medium text-zinc-700 dark:text-zinc-300">1,284</span>{" "}
                pages generated this week
              </span>
            </div>
            <span className="hidden sm:inline text-zinc-300 dark:text-zinc-800">·</span>
            <a
              href="https://github.com/jesusbernalrj/inari-pages"
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 hover:text-zinc-900 dark:hover:text-zinc-100 transition"
            >
              <GithubIcon size={12} />
              <span>Star on GitHub</span>
              <span className="inline-flex items-center gap-1 rounded-full bg-zinc-100 dark:bg-zinc-900 px-1.5 py-0.5 text-[10.5px] font-medium tabular-nums text-zinc-600 dark:text-zinc-400">
                <Star size={9} className="text-amber-500" />
                2.4k
              </span>
            </a>
          </div>

          <div className="mt-14 w-full">
            <div className="text-[11px] uppercase tracking-[0.18em] text-zinc-400 dark:text-zinc-600 mb-3">
              Generated by Inari, in seconds →
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {[<ThumbAcme key="acme" />, <ThumbBloom key="bloom" />, <ThumbDrift key="drift" />].map(
                (t, i) => (
                  <div key={i} className="group relative">
                    <div className="transform transition duration-300 hover:-translate-y-1 hover:rotate-[-0.4deg]">
                      {t}
                    </div>
                  </div>
                ),
              )}
            </div>
          </div>
        </div>
      </div>

      <div
        className="pointer-events-none absolute inset-x-0 bottom-0 h-24 bg-gradient-to-b from-transparent to-white dark:to-[#0a0a0a]"
        aria-hidden
      />
    </section>
  );
}
