// Curated Lucide icon registry — the subset shown in the icon picker.
// We don't expose all 1,400+ icons because (a) bundle bloat, (b) decision
// paralysis. This is the ~120 icons most useful for SaaS landing pages.
// Add more here as needed.

import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AtSign,
  Award,
  BarChart,
  BarChart2,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsRight,
  Clock,
  Cloud,
  Code,
  Code2,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  File,
  FileCheck,
  FileCode,
  FilePlus,
  FileText,
  Filter,
  Flame,
  Folder,
  FolderOpen,
  Gift,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Globe,
  Headphones,
  Heart,
  HelpCircle,
  Image as ImageIcon,
  Inbox,
  Info,
  Key,
  Layers,
  LineChart,
  Link,
  Loader,
  Loader2,
  Lock,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Music,
  Package,
  Pause,
  Phone,
  PieChart,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Sun,
  Target,
  Terminal,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Unlock,
  User,
  Users,
  Video,
  Volume2,
  Wand2,
  X,
  XCircle,
  Zap,
} from "lucide-react";

export type IconCategory =
  | "nav"
  | "status"
  | "ui"
  | "comm"
  | "files"
  | "tech"
  | "business"
  | "productivity"
  | "media"
  | "misc";

export interface CuratedIcon {
  /** kebab-case name — what the user searches. */
  name: string;
  Component: LucideIcon;
  category: IconCategory;
}

export const CURATED_ICONS: CuratedIcon[] = [
  // Navigation / arrows
  { name: "arrow-right", Component: ArrowRight, category: "nav" },
  { name: "arrow-left", Component: ArrowLeft, category: "nav" },
  { name: "arrow-up", Component: ArrowUp, category: "nav" },
  { name: "arrow-down", Component: ArrowDown, category: "nav" },
  { name: "arrow-up-right", Component: ArrowUpRight, category: "nav" },
  { name: "arrow-down-right", Component: ArrowDownRight, category: "nav" },
  { name: "chevron-right", Component: ChevronRight, category: "nav" },
  { name: "chevron-left", Component: ChevronLeft, category: "nav" },
  { name: "chevron-up", Component: ChevronUp, category: "nav" },
  { name: "chevron-down", Component: ChevronDown, category: "nav" },
  { name: "chevrons-right", Component: ChevronsRight, category: "nav" },
  { name: "external-link", Component: ExternalLink, category: "nav" },
  { name: "menu", Component: Menu, category: "nav" },
  { name: "more-horizontal", Component: MoreHorizontal, category: "nav" },
  { name: "more-vertical", Component: MoreVertical, category: "nav" },

  // Status
  { name: "check", Component: Check, category: "status" },
  { name: "check-circle", Component: CheckCircle, category: "status" },
  { name: "check-circle-2", Component: CheckCircle2, category: "status" },
  { name: "x", Component: X, category: "status" },
  { name: "x-circle", Component: XCircle, category: "status" },
  { name: "alert-circle", Component: AlertCircle, category: "status" },
  { name: "alert-triangle", Component: AlertTriangle, category: "status" },
  { name: "info", Component: Info, category: "status" },
  { name: "help-circle", Component: HelpCircle, category: "status" },
  { name: "loader", Component: Loader, category: "status" },
  { name: "loader-2", Component: Loader2, category: "status" },
  { name: "refresh-cw", Component: RefreshCw, category: "status" },

  // Common UI
  { name: "plus", Component: Plus, category: "ui" },
  { name: "minus", Component: Minus, category: "ui" },
  { name: "settings", Component: Settings, category: "ui" },
  { name: "search", Component: Search, category: "ui" },
  { name: "filter", Component: Filter, category: "ui" },
  { name: "bell", Component: Bell, category: "ui" },
  { name: "star", Component: Star, category: "ui" },
  { name: "heart", Component: Heart, category: "ui" },
  { name: "bookmark", Component: Bookmark, category: "ui" },
  { name: "share", Component: Share, category: "ui" },
  { name: "share-2", Component: Share2, category: "ui" },
  { name: "copy", Component: Copy, category: "ui" },
  { name: "edit", Component: Edit, category: "ui" },
  { name: "trash-2", Component: Trash2, category: "ui" },
  { name: "eye", Component: Eye, category: "ui" },

  // Communication
  { name: "mail", Component: Mail, category: "comm" },
  { name: "message-circle", Component: MessageCircle, category: "comm" },
  { name: "message-square", Component: MessageSquare, category: "comm" },
  { name: "phone", Component: Phone, category: "comm" },
  { name: "send", Component: Send, category: "comm" },
  { name: "inbox", Component: Inbox, category: "comm" },
  { name: "at-sign", Component: AtSign, category: "comm" },
  { name: "link", Component: Link, category: "comm" },

  // Files
  { name: "file", Component: File, category: "files" },
  { name: "file-text", Component: FileText, category: "files" },
  { name: "file-code", Component: FileCode, category: "files" },
  { name: "file-check", Component: FileCheck, category: "files" },
  { name: "file-plus", Component: FilePlus, category: "files" },
  { name: "folder", Component: Folder, category: "files" },
  { name: "folder-open", Component: FolderOpen, category: "files" },
  { name: "save", Component: Save, category: "files" },
  { name: "archive", Component: Archive, category: "files" },
  { name: "download", Component: Download, category: "files" },

  // Tech / code
  { name: "code", Component: Code, category: "tech" },
  { name: "code-2", Component: Code2, category: "tech" },
  { name: "terminal", Component: Terminal, category: "tech" },
  { name: "git-branch", Component: GitBranch, category: "tech" },
  { name: "git-commit", Component: GitCommit, category: "tech" },
  { name: "git-pull-request", Component: GitPullRequest, category: "tech" },
  { name: "cpu", Component: Cpu, category: "tech" },
  { name: "database", Component: Database, category: "tech" },
  { name: "server", Component: Server, category: "tech" },
  { name: "cloud", Component: Cloud, category: "tech" },
  { name: "lock", Component: Lock, category: "tech" },
  { name: "unlock", Component: Unlock, category: "tech" },
  { name: "key", Component: Key, category: "tech" },
  { name: "shield", Component: Shield, category: "tech" },
  { name: "shield-check", Component: ShieldCheck, category: "tech" },

  // Business / metrics
  { name: "bar-chart", Component: BarChart, category: "business" },
  { name: "bar-chart-2", Component: BarChart2, category: "business" },
  { name: "bar-chart-3", Component: BarChart3, category: "business" },
  { name: "line-chart", Component: LineChart, category: "business" },
  { name: "pie-chart", Component: PieChart, category: "business" },
  { name: "trending-up", Component: TrendingUp, category: "business" },
  { name: "trending-down", Component: TrendingDown, category: "business" },
  { name: "activity", Component: Activity, category: "business" },
  { name: "dollar-sign", Component: DollarSign, category: "business" },
  { name: "credit-card", Component: CreditCard, category: "business" },
  { name: "briefcase", Component: Briefcase, category: "business" },
  { name: "building-2", Component: Building2, category: "business" },

  // Productivity
  { name: "calendar", Component: Calendar, category: "productivity" },
  { name: "clock", Component: Clock, category: "productivity" },
  { name: "timer", Component: Timer, category: "productivity" },
  { name: "zap", Component: Zap, category: "productivity" },
  { name: "rocket", Component: Rocket, category: "productivity" },
  { name: "target", Component: Target, category: "productivity" },
  { name: "compass", Component: Compass, category: "productivity" },
  { name: "map", Component: Map, category: "productivity" },
  { name: "map-pin", Component: MapPin, category: "productivity" },
  { name: "globe", Component: Globe, category: "productivity" },

  // Media
  { name: "play", Component: Play, category: "media" },
  { name: "pause", Component: Pause, category: "media" },
  { name: "video", Component: Video, category: "media" },
  { name: "camera", Component: Camera, category: "media" },
  { name: "image", Component: ImageIcon, category: "media" },
  { name: "mic", Component: Mic, category: "media" },
  { name: "mic-off", Component: MicOff, category: "media" },
  { name: "volume-2", Component: Volume2, category: "media" },
  { name: "music", Component: Music, category: "media" },
  { name: "headphones", Component: Headphones, category: "media" },

  // Misc
  { name: "sparkles", Component: Sparkles, category: "misc" },
  { name: "wand-2", Component: Wand2, category: "misc" },
  { name: "award", Component: Award, category: "misc" },
  { name: "trophy", Component: Trophy, category: "misc" },
  { name: "gift", Component: Gift, category: "misc" },
  { name: "flame", Component: Flame, category: "misc" },
  { name: "sun", Component: Sun, category: "misc" },
  { name: "moon", Component: Moon, category: "misc" },
  { name: "layers", Component: Layers, category: "misc" },
  { name: "box", Component: Box, category: "misc" },
  { name: "package", Component: Package, category: "misc" },
  { name: "truck", Component: Truck, category: "misc" },
  { name: "shopping-cart", Component: ShoppingCart, category: "misc" },
  { name: "users", Component: Users, category: "misc" },
  { name: "user", Component: User, category: "misc" },
];

export const CATEGORY_LABELS: Record<IconCategory, string> = {
  nav: "Navigation",
  status: "Status",
  ui: "UI",
  comm: "Communication",
  files: "Files",
  tech: "Tech",
  business: "Business",
  productivity: "Productivity",
  media: "Media",
  misc: "Misc",
};
