// Lookup table: Lucide icon name → inline SVG markup string.
//
// Canva-mode stores `props.name` on Icon nodes (e.g. "check"). The compiler
// needs the actual SVG to inline at render — without this, every Icon node
// would compile to an empty <span>, invisible on the canvas.
//
// The map itself is BAKED — generated by scripts/bake-lucide-svgs.ts. We
// can't render it at runtime because Next.js disallows react-dom/server
// inside server components (which compile.ts ends up in). Re-bake via
// `npm run bake:lucide` after editing CURATED_ICONS.

import { LUCIDE_SVGS } from "./lucide-svgs.generated";

/** Returns the inline SVG markup for a Lucide icon name, or null if it is
 *  not in our curated set. */
export function getLucideSvg(name: string): string | null {
  return LUCIDE_SVGS[name] ?? null;
}
