// Starter pack — GLBs that ship in-repo so a fresh OpenLen deploy has models
// to show in the 3D panel immediately.
//
// To seed an instance: `npm run models:seed`. That uploads each GLB to
// object storage and inserts a row in `models`. After seed, add more via
// `npm run models:add`.
//
// Contents:
//   - 2 objects from the Khronos glTF Sample Assets repository
//     (https://github.com/KhronosGroup/glTF-Sample-Assets), CC-BY 4.0.
//   - 3 procedural DECORATIVE sculptures generated by OpenLen (scratch/
//     procgen-scene.js → GLTFExporter), CC0.

import type { ModelFamily } from "@/lib/models/families";

export interface StarterModelEntry {
  id: string;
  name: string;
  family: ModelFamily;
  author: string;
  pitch: string;
  description: string;
  fileName: string;
  license: string;
}

export const STARTER_MODELS: StarterModelEntry[] = [
  {
    id: "damaged-helmet",
    name: "Damaged Helmet",
    family: "mechanical",
    author: "ctxwing — Khronos glTF Sample Assets (CC-BY-4.0)",
    pitch: "Casco battle-worn de ciencia ficción con materiales PBR de referencia.",
    description:
      "Casco de astronauta con daños de combate y materiales PBR de alta fidelidad. Referencia clásica del ecosistema glTF — ideal para páginas de tecnología, juegos o sci-fi.",
    fileName: "helmet.glb",
    license: "cc-by-4.0",
  },
  {
    id: "materials-shoe",
    name: "Materials Shoe",
    family: "product",
    author: "Shopify / Khronos glTF Sample Assets (CC-BY-4.0)",
    pitch: "Sneaker de exhibición para páginas de moda y e-commerce.",
    description:
      "Tenis de alto detalle con múltiples variantes de material, ideal para hero-shots de e-commerce, páginas de moda o demostraciones de producto 3D.",
    fileName: "shoe.glb",
    license: "cc-by-4.0",
  },
  {
    id: "deco-crystal",
    name: "Racimo de cristal",
    family: "decorative",
    author: "OpenLen (procedural)",
    pitch: "Racimo de gemas facetadas con brillo iridiscente.",
    description:
      "Formación de cristales facetados con material iridiscente-metálico, generada proceduralmente. Elemento decorativo abstracto para heros elegantes y oscuros.",
    fileName: "deco-crystal.glb",
    license: "cc0",
  },
  {
    id: "deco-ribbon",
    name: "Cinta cromada",
    family: "decorative",
    author: "OpenLen (procedural)",
    pitch: "Nudo de cinta metálica que fluye, cromo pulido.",
    description:
      "Escultura de cinta metálica siguiendo una curva trefoil, en cromo pulido. Forma decorativa fluida y premium para cualquier página.",
    fileName: "deco-ribbon.glb",
    license: "cc0",
  },
  {
    id: "deco-organic",
    name: "Forma orgánica",
    family: "decorative",
    author: "OpenLen (procedural)",
    pitch: "Escultura orgánica lisa con acabado perla iridiscente.",
    description:
      "Forma orgánica desplazada con material perla iridiscente y clearcoat. Escultura decorativa suave, ideal como pieza central de hero.",
    fileName: "deco-organic.glb",
    license: "cc0",
  },
  {
    id: "deco-urchin",
    name: "Estrella de púas",
    family: "decorative",
    author: "OpenLen (procedural)",
    pitch: "Estallido radial de púas cromadas con núcleo iridiscente.",
    description:
      "Escultura tipo erizo: núcleo iridiscente rodeado de púas metálicas que irradian en todas direcciones. Pieza decorativa llamativa para heros con carácter.",
    fileName: "deco-urchin.glb",
    license: "cc0",
  },
  {
    id: "deco-gyre",
    name: "Esfera armilar",
    family: "decorative",
    author: "OpenLen (procedural)",
    pitch: "Anillos cromados inclinados anidados, tipo giroscopio.",
    description:
      "Conjunto de anillos metálicos inclinados y anidados que forman una esfera armilar. Escultura decorativa elegante e intrincada, evoca órbitas o instrumentos antiguos.",
    fileName: "deco-gyre.glb",
    license: "cc0",
  },
];
