import type { SceneSpec } from "./scene-spec";

export const GOLDEN: { brief: string; spec: SceneSpec }[] = [
  { brief: "un anillo de oro girando lento", spec: { version: 1, preset: "accent", geometry: { kind: "torus", params: { scale: 0.6, detail: 0.6, distort: 0.05, density: 0.5 } }, material: { kind: "metal", roughness: 0.2, metalness: 1, opacity: 1, accentLinked: false, colors: ["#E8B007"] }, motion: { kind: "drift", speed: 0.3, amplitude: 0.4 }, look: "dramatic", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "cristales de vidrio flotando", spec: { version: 1, preset: "background", geometry: { kind: "icosa", params: { scale: 0.5, detail: 0.2, distort: 0.1, density: 0.7 } }, material: { kind: "glass", roughness: 0.05, metalness: 0, opacity: 0.7, accentLinked: false, colors: ["#BFE9FF"] }, motion: { kind: "drift", speed: 0.25, amplitude: 0.6 }, look: "soft", camera: { framing: "wide" }, background: "transparent" } },
  { brief: "una esfera iridiscente", spec: { version: 1, preset: "background", geometry: { kind: "sphere", params: { scale: 0.7, detail: 0.7, distort: 0.45, density: 0.5 } }, material: { kind: "iridescent", roughness: 0.25, metalness: 0.8, opacity: 1, accentLinked: false, colors: ["#7C5CFF", "#FF5A36"] }, motion: { kind: "drift", speed: 0.35, amplitude: 0.5 }, look: "dramatic", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "un campo de particulas brillantes", spec: { version: 1, preset: "background", geometry: { kind: "particles", params: { scale: 0.4, detail: 0.5, distort: 0.2, density: 0.9 } }, material: { kind: "emissive", roughness: 1, metalness: 0, opacity: 1, accentLinked: true, colors: ["#7C5CFF"] }, motion: { kind: "drift", speed: 0.2, amplitude: 0.7 }, look: "neutral", camera: { framing: "wide" }, background: "transparent" } },
  { brief: "un blob de cromo liquido", spec: { version: 1, preset: "accent", geometry: { kind: "blob", params: { scale: 0.7, detail: 0.6, distort: 0.6, density: 0.5 } }, material: { kind: "chrome", roughness: 0.05, metalness: 1, opacity: 1, accentLinked: false, colors: ["#C8CDD4"] }, motion: { kind: "drift", speed: 0.3, amplitude: 0.5 }, look: "studio", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "un nudo toroidal metalico", spec: { version: 1, preset: "accent", geometry: { kind: "torusKnot", params: { scale: 0.6, detail: 0.7, distort: 0, density: 0.5 } }, material: { kind: "metal", roughness: 0.3, metalness: 0.9, opacity: 1, accentLinked: true, colors: ["#FF5A36"] }, motion: { kind: "rotate", speed: 0.5, amplitude: 0 }, look: "dramatic", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "un icosaedro de obsidiana mate", spec: { version: 1, preset: "accent", geometry: { kind: "icosa", params: { scale: 0.6, detail: 0.1, distort: 0, density: 0.5 } }, material: { kind: "matte", roughness: 0.8, metalness: 0.1, opacity: 1, accentLinked: false, colors: ["#16171A"] }, motion: { kind: "rotate", speed: 0.25, amplitude: 0 }, look: "studio", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "una onda de gradiente suave", spec: { version: 1, preset: "background", geometry: { kind: "plane", params: { scale: 1, detail: 0.8, distort: 0.5, density: 0.5 } }, material: { kind: "gradient", roughness: 0.6, metalness: 0, opacity: 1, accentLinked: true, colors: ["#7C5CFF", "#FF5A36"] }, motion: { kind: "drift", speed: 0.2, amplitude: 0.4 }, look: "soft", camera: { framing: "wide" }, background: "gradient" } },
  { brief: "una gema flotante color marca", spec: { version: 1, preset: "accent", geometry: { kind: "icosa", params: { scale: 0.5, detail: 0.05, distort: 0, density: 0.5 } }, material: { kind: "glass", roughness: 0.1, metalness: 0.2, opacity: 0.85, accentLinked: true, colors: ["#FF5A36"] }, motion: { kind: "drift", speed: 0.3, amplitude: 0.5 }, look: "dramatic", camera: { framing: "centered" }, background: "transparent" } },
  { brief: "una esfera de ruido organico quieta", spec: { version: 1, preset: "accent", geometry: { kind: "sphere", params: { scale: 0.7, detail: 0.8, distort: 0.6, density: 0.5 } }, material: { kind: "matte", roughness: 0.7, metalness: 0.2, opacity: 1, accentLinked: true, colors: ["#7C5CFF"] }, motion: { kind: "still", speed: 0, amplitude: 0 }, look: "soft", camera: { framing: "centered" }, background: "transparent" } },
];
