import type { SelectorEvalCase } from "./selector-cases";

export const SELECTOR_HOLDOUT_CASES: readonly SelectorEvalCase[] = [
  {
    id: "legal-firm-holdout-en",
    language: "en",
    brief: "Boutique employment law firm for startup founders, with attorney profiles, case insights, consultation booking and transparent services.",
    expectedDomains: ["legal_services", "business_services"],
    expectedAudience: "businesses",
    forbiddenSignals: ["children_toy_ui", "gaming_esports"],
    adversarial: true,
  },
  {
    id: "logistics-holdout-es",
    language: "es",
    brief: "Empresa de logística para comercios con envíos nacionales, rastreo, cobertura, cotización y casos de clientes.",
    expectedDomains: ["logistics", "business_services"],
    expectedAudience: "businesses",
    forbiddenSignals: ["children_toy_ui", "luxury_beauty"],
    adversarial: false,
  },
  {
    id: "research-lab-holdout-en",
    language: "en",
    brief: "University climate research lab with current projects, datasets, publications, team profiles and opportunities for research partners.",
    expectedDomains: ["science", "education"],
    expectedAudience: "professionals",
    forbiddenSignals: ["restaurant_menu", "children_toy_ui"],
    adversarial: false,
  },
  {
    id: "musician-holdout-es",
    language: "es",
    brief: "Sitio de una cantautora independiente con lanzamientos, videos, próximas fechas, biografía, prensa y enlaces para escuchar.",
    expectedDomains: ["music", "portfolio"],
    expectedAudience: "fans",
    forbiddenSignals: ["saas_dashboard", "medical_clinical"],
    adversarial: true,
  },
  {
    id: "photographer-holdout-en",
    language: "en",
    brief: "Documentary wedding photographer with selected stories, approach, packages, availability and an inquiry form for couples.",
    expectedDomains: ["photography", "portfolio"],
    expectedAudience: "consumers",
    forbiddenSignals: ["course_progress_ui", "developer_terminal"],
    adversarial: true,
  },
  {
    id: "coworking-holdout-es",
    language: "es",
    brief: "Espacio de coworking de barrio con membresías, salas de juntas, eventos, amenidades, recorridos y reserva de escritorios.",
    expectedDomains: ["coworking", "local_services"],
    expectedAudience: "professionals",
    forbiddenSignals: ["children_toy_ui", "medical_clinical"],
    adversarial: false,
  },
  {
    id: "city-portal-holdout-en",
    language: "en",
    brief: "City services portal for permits, waste pickup, public transit updates, council meetings and emergency notices.",
    expectedDomains: ["government", "local_services"],
    expectedAudience: "citizens",
    forbiddenSignals: ["gaming_esports", "luxury_beauty"],
    adversarial: true,
  },
  {
    id: "conference-holdout-es",
    language: "es",
    brief: "Conferencia profesional sobre inteligencia artificial con ponentes, agenda, talleres, sede, patrocinadores y venta de entradas.",
    expectedDomains: ["events", "ai_ml"],
    expectedAudience: "professionals",
    forbiddenSignals: ["restaurant_menu", "children_toy_ui"],
    adversarial: false,
  },
  {
    id: "beauty-salon-holdout-en",
    language: "en",
    brief: "Independent hair salon with stylist profiles, cut and color services, pricing, client transformations and online booking.",
    expectedDomains: ["beauty", "local_services"],
    expectedAudience: "consumers",
    forbiddenSignals: ["developer_terminal", "gaming_esports"],
    adversarial: false,
  },
  {
    id: "contractor-holdout-es",
    language: "es",
    brief: "Constructora residencial con proyectos terminados, proceso de obra, equipo, garantías y solicitud de presupuesto para propietarios.",
    expectedDomains: ["construction", "local_services"],
    expectedAudience: "homeowners",
    forbiddenSignals: ["children_toy_ui", "luxury_editorial"],
    adversarial: true,
  },
];
