export interface SelectorEvalCase {
  id: string;
  language: "es" | "en";
  brief: string;
  expectedDomains: string[];
  expectedAudience: string;
  forbiddenSignals: string[];
  adversarial: boolean;
}

export const SELECTOR_CASES: SelectorEvalCase[] = [
  { id: "kids-coloring-es", language: "es", brief: "Plataforma infantil de coloreo con pÃ¡ginas para colorear, minijuegos, cuentos y actividades creativas.", expectedDomains: ["children_entertainment", "creative_play"], expectedAudience: "children", forbiddenSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], adversarial: true },
  { id: "kids-stories-en", language: "en", brief: "A magical illustrated story and drawing club for children ages 6 to 9, with printable activities for parents.", expectedDomains: ["children_entertainment", "creative_play"], expectedAudience: "children", forbiddenSignals: ["saas_dashboard", "luxury_editorial"], adversarial: true },
  { id: "language-school-es", language: "es", brief: "Academia online para adultos que aprenden inglÃ©s con clases, progreso, certificados y tutores.", expectedDomains: ["education"], expectedAudience: "adults", forbiddenSignals: ["children_toy_ui", "gaming_esports"], adversarial: true },
  { id: "preschool-es", language: "es", brief: "Preescolar para familias con aprendizaje mediante juego, horarios, maestras, admisiones y recorridos del campus.", expectedDomains: ["education", "local_services"], expectedAudience: "parents", forbiddenSignals: ["saas_dashboard", "nightclub"], adversarial: true },
  { id: "dev-observability-en", language: "en", brief: "Developer observability platform for tracing AI agents in production, with spans, costs, alerts and API docs.", expectedDomains: ["developer_tools", "ai_ml"], expectedAudience: "developers", forbiddenSignals: ["children_toy_ui", "wellness_organic"], adversarial: false },
  { id: "coffee-es", language: "es", brief: "Tostador independiente de cafÃ© de especialidad con suscripciÃ³n, notas de cata, orÃ­genes y visitas al taller.", expectedDomains: ["food_beverage"], expectedAudience: "consumers", forbiddenSignals: ["saas_dashboard", "medical_clinical"], adversarial: false },
  { id: "restaurant-en", language: "en", brief: "Warm neighborhood Italian restaurant with seasonal menu, reservations, chef story and private dining.", expectedDomains: ["food_beverage", "hospitality"], expectedAudience: "consumers", forbiddenSignals: ["developer_terminal", "course_progress_ui"], adversarial: false },
  { id: "wellness-es", language: "es", brief: "Estudio de yoga y respiraciÃ³n para mujeres, con clases, retiros, instructoras y reserva de sesiÃ³n.", expectedDomains: ["wellness"], expectedAudience: "adults", forbiddenSignals: ["gaming_esports", "corporate_dashboard"], adversarial: false },
  { id: "dentist-es", language: "es", brief: "ClÃ­nica dental familiar con tratamientos, doctores, testimonios, urgencias y reserva por WhatsApp.", expectedDomains: ["healthcare", "local_services"], expectedAudience: "families", forbiddenSignals: ["saas_dashboard", "nightclub"], adversarial: false },
  { id: "fintech-en", language: "en", brief: "Mobile banking app for freelancers with invoices, tax envelopes, instant transfers and transparent pricing.", expectedDomains: ["fintech"], expectedAudience: "professionals", forbiddenSignals: ["children_toy_ui", "restaurant_menu"], adversarial: false },
  { id: "artist-portfolio-es", language: "es", brief: "Portafolio de una ilustradora editorial con proyectos seleccionados, biografÃ­a, exposiciones y contacto.", expectedDomains: ["portfolio", "illustration"], expectedAudience: "creative_clients", forbiddenSignals: ["saas_dashboard", "course_progress_ui"], adversarial: true },
  { id: "design-agency-en", language: "en", brief: "Boutique brand design studio with selected work, point of view, services and a project inquiry form.", expectedDomains: ["agency", "portfolio"], expectedAudience: "businesses", forbiddenSignals: ["children_toy_ui", "medical_clinical"], adversarial: false },
  { id: "indie-game-es", language: "es", brief: "Videojuego indie cooperativo de fantasÃ­a con trÃ¡iler, personajes, mundo, novedades y lista de deseos.", expectedDomains: ["gaming"], expectedAudience: "gamers", forbiddenSignals: ["course_progress_ui", "corporate_photography"], adversarial: true },
  { id: "sports-club-en", language: "en", brief: "Community football club with fixtures, standings, youth teams, tickets and match-day news.", expectedDomains: ["sports"], expectedAudience: "fans", forbiddenSignals: ["saas_dashboard", "luxury_beauty"], adversarial: false },
  { id: "wedding-es", language: "es", brief: "Sitio de boda Ã­ntima con historia de la pareja, itinerario, ubicaciÃ³n, hospedaje y confirmaciÃ³n de asistencia.", expectedDomains: ["wedding"], expectedAudience: "guests", forbiddenSignals: ["saas_dashboard", "gaming_esports"], adversarial: false },
  { id: "nonprofit-en", language: "en", brief: "Local literacy nonprofit with impact stories, volunteer opportunities, donation options and annual reports.", expectedDomains: ["nonprofit"], expectedAudience: "donors", forbiddenSignals: ["ecommerce_storefront", "gaming_esports"], adversarial: false },
  { id: "fashion-es", language: "es", brief: "Marca de moda sostenible con colecciÃ³n editorial, materiales, lookbook, tallas y tienda online.", expectedDomains: ["fashion", "ecommerce"], expectedAudience: "consumers", forbiddenSignals: ["saas_dashboard", "developer_terminal"], adversarial: true },
  { id: "real-estate-en", language: "en", brief: "Boutique real-estate brokerage for design-led homes with listings, neighborhood guides and valuation requests.", expectedDomains: ["real_estate"], expectedAudience: "home_buyers", forbiddenSignals: ["course_progress_ui", "children_toy_ui"], adversarial: false },
  { id: "hardware-es", language: "es", brief: "Dispositivo domÃ©stico para medir la calidad del aire con sensores, aplicaciÃ³n, especificaciones y preventa.", expectedDomains: ["hardware", "consumer_technology"], expectedAudience: "consumers", forbiddenSignals: ["restaurant_menu", "children_toy_ui"], adversarial: false },
  { id: "editorial-en", language: "en", brief: "Independent culture magazine with long-form essays, issue archive, contributors and a paid print subscription.", expectedDomains: ["editorial", "publishing"], expectedAudience: "readers", forbiddenSignals: ["saas_dashboard", "course_progress_ui"], adversarial: false },
];
