import { z } from "zod";
import { IntentAnalysisSchema, TaxonomySlugSchema } from "./contracts";

export const VISUAL_ENGINE_2A_DATASET_VERSION = "visual-engine-2a-cohort/1.0" as const;

export const VisualEngine2APilotCaseSchema = z.object({
  id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  datasetVersion: z.literal(VISUAL_ENGINE_2A_DATASET_VERSION),
  archetype: z.enum([
    "children_creative", "restaurant_hospitality", "wellness",
    "technical_saas", "editorial_portfolio",
  ]),
  language: z.enum(["es", "en"]),
  briefLength: z.enum(["short", "medium", "detailed"]),
  brief: z.string().min(1).max(2_000),
  expectedIntent: IntentAnalysisSchema,
  allowedSkeletonTemplateIds: z.array(z.string().min(1)).min(1),
  identityConflict: z.object({
    structuralPattern: z.string().min(1).max(500),
    baselineIdentity: z.string().min(1).max(500),
    requestedIdentity: z.string().min(1).max(500),
  }).strict(),
  requiredVisualSignals: z.array(TaxonomySlugSchema).min(1),
  forbiddenVisualSignals: z.array(TaxonomySlugSchema).min(1),
  structuralRationale: z.string().min(1).max(1_000),
}).strict();

export type VisualEngine2APilotCase = z.infer<typeof VisualEngine2APilotCaseSchema>;

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const nestedValue of Object.values(value)) deepFreeze(nestedValue);
  }
  return value;
}

const COHORT_ROWS = [
  {
    id: "creative-club-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "children_creative", language: "es", briefLength: "short",
    brief: "Club infantil presencial de arte con sesiones, galería y registro familiar; identity: cut-paper, crayon, joyful primary colors",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "business", requiredSections: ["hero", "about", "services", "gallery", "contact"], primaryActions: ["family_registration"], contentModel: "children_art_club" }, audience: { primary: "children", ageRange: "6_12", secondary: ["families"] }, domains: ["education", "creative_play"], emotionalGoals: ["joyful", "creative"], requiredVisualSignals: ["cut_paper", "crayon", "joyful_primary_colors"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["rompiente"], identityConflict: { structuralPattern: "business pattern with hero, about, services, gallery, and contact", baselineIdentity: "reviewed rompiente baseline identity", requestedIdentity: "cut-paper, crayon, joyful primary colors" }, requiredVisualSignals: ["cut_paper", "crayon", "joyful_primary_colors"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], structuralRationale: "Retains the hero, about, services, gallery, and contact roles; the art club requires no role change." },
  {
    id: "printable-library-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "children_creative", language: "en", briefLength: "medium",
    brief: "Parent-facing printable activity collection with themed packs, program explanation, FAQ, and download CTA; identity: pastel sticker-book",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "educational_resource", requiredSections: ["hero", "about", "programs", "call_to_action", "faq", "footer"], primaryActions: ["download"], contentModel: "printable_activity_collection" }, audience: { primary: "parents", ageRange: "5_10", secondary: ["children"] }, domains: ["education", "creative_play"], emotionalGoals: ["playful", "friendly"], requiredVisualSignals: ["pastel", "sticker_book"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["lantern"], identityConflict: { structuralPattern: "educational resource pattern with hero, about, programs, CTA, FAQ, and footer", baselineIdentity: "reviewed lantern baseline identity", requestedIdentity: "pastel sticker-book" }, requiredVisualSignals: ["pastel", "sticker_book"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], structuralRationale: "Retains the hero, about, programs, CTA, FAQ, and footer roles; themed packs and downloads require no role change." },
  {
    id: "teacher-art-hub-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "children_creative", language: "en", briefLength: "detailed",
    brief: "Creator hub for an art educator with profile, resource links, featured projects, events, and social links; identity: classroom collage without course-progress UI",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "creator_hub", requiredSections: ["header", "profile_summary", "link_list", "featured_content", "social_links", "footer"], primaryActions: ["resource_links", "social_links"], contentModel: "art_educator_creator_hub" }, audience: { primary: "educators", ageRange: "18_plus", secondary: [] }, domains: ["education", "creative_play"], emotionalGoals: ["creative", "approachable"], requiredVisualSignals: ["classroom_collage"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], explicitConstraints: ["without course-progress UI"], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["enlace"], identityConflict: { structuralPattern: "creator hub pattern with header, profile summary, link list, featured content, social links, and footer", baselineIdentity: "reviewed enlace baseline identity", requestedIdentity: "classroom collage without course-progress UI" }, requiredVisualSignals: ["classroom_collage"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui", "corporate_photography"], structuralRationale: "Retains the header, profile summary, link list, featured content, social links, and footer roles; educator resources and events require no role change." },
  {
    id: "taqueria-pop-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "restaurant_hospitality", language: "es", briefLength: "short",
    brief: "Taquería neighborhood site with menu, gallery, reservations, and contact; identity: vivid papel-picado pop",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "restaurant", requiredSections: ["hero", "about", "menu", "gallery", "reservations", "contact", "footer"], primaryActions: ["reservations"], contentModel: "taqueria" }, audience: { primary: "consumers", ageRange: null, secondary: [] }, domains: ["food_beverage", "hospitality"], emotionalGoals: ["vivid", "welcoming"], requiredVisualSignals: ["papel_picado", "vivid_pop"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["mesa"], identityConflict: { structuralPattern: "restaurant pattern with hero, about, menu, gallery, reservations, contact, and footer", baselineIdentity: "reviewed mesa baseline identity", requestedIdentity: "vivid papel-picado pop" }, requiredVisualSignals: ["papel_picado", "vivid_pop"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], structuralRationale: "Retains the hero, about, menu, gallery, reservations, contact, and footer roles; neighborhood dining requires no role change." },
  {
    id: "bakery-morning-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "restaurant_hospitality", language: "en", briefLength: "medium",
    brief: "Bakery/café presence with story, menu, gallery, reviews, location, and order CTA; identity: bright risograph morning market",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "business", requiredSections: ["hero", "about", "menu", "gallery", "testimonials", "contact", "call_to_action", "footer"], primaryActions: ["order"], contentModel: "bakery_cafe" }, audience: { primary: "consumers", ageRange: null, secondary: [] }, domains: ["food_beverage", "hospitality"], emotionalGoals: ["bright", "welcoming"], requiredVisualSignals: ["risograph", "morning_market"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["cafe-tramonto"], identityConflict: { structuralPattern: "business pattern with hero, about, menu, gallery, testimonials, contact, CTA, and footer", baselineIdentity: "reviewed cafe-tramonto baseline identity", requestedIdentity: "bright risograph morning market" }, requiredVisualSignals: ["risograph", "morning_market"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], structuralRationale: "Retains the hero, about, menu, gallery, testimonials, contact, CTA, and footer roles; bakery story, location, and ordering require no role change." },
  {
    id: "botanical-winebar-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "restaurant_hospitality", language: "es", briefLength: "detailed",
    brief: "Daytime botanical wine bar with menu, events, reservation, origin story, and contact; identity: airy garden editorial, explicitly not dark nightlife",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "restaurant_website", requiredSections: ["hero", "about", "menu", "events", "reservations", "contact", "footer"], primaryActions: ["reservations"], contentModel: "botanical_wine_bar" }, audience: { primary: "consumers", ageRange: null, secondary: [] }, domains: ["food_beverage", "hospitality"], emotionalGoals: ["airy", "editorial"], requiredVisualSignals: ["botanical", "garden_editorial"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], explicitConstraints: ["not dark nightlife"], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["tanino"], identityConflict: { structuralPattern: "restaurant website pattern with hero, about, menu, events, reservations, contact, and footer", baselineIdentity: "reviewed tanino baseline identity", requestedIdentity: "airy garden editorial, not dark nightlife" }, requiredVisualSignals: ["botanical", "garden_editorial"], forbiddenVisualSignals: ["developer_terminal", "course_progress_ui"], structuralRationale: "Retains the hero, about, menu, events, reservations, contact, and footer roles; daytime wine-bar events and reservations require no role change." },
  {
    id: "breathwork-studio-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "wellness", language: "en", briefLength: "short",
    brief: "Breathwork studio with services, pricing, team, and booking; identity: energetic cobalt/coral geometry",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "small_business", requiredSections: ["hero", "about", "services", "team", "pricing", "contact"], primaryActions: ["booking"], contentModel: "breathwork_studio" }, audience: { primary: "adults", ageRange: null, secondary: [] }, domains: ["wellness"], emotionalGoals: ["energetic", "confident"], requiredVisualSignals: ["cobalt", "coral", "geometry"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["aire-estudio"], identityConflict: { structuralPattern: "small business pattern with hero, about, services, team, pricing, and contact", baselineIdentity: "reviewed aire-estudio baseline identity", requestedIdentity: "energetic cobalt/coral geometry" }, requiredVisualSignals: ["cobalt", "coral", "geometry"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], structuralRationale: "Retains the hero, about, services, team, pricing, and contact roles; breathwork booking requires no role change." },
  {
    id: "sleep-community-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "wellness", language: "es", briefLength: "medium",
    brief: "Comunidad de descanso con prácticas, calendario, membresía, testimonios y contacto; identity: dreamy midnight sky and soft constellations",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "community_hub", requiredSections: ["hero", "about", "services", "schedule", "pricing", "testimonials", "contact"], primaryActions: ["membership"], contentModel: "sleep_community" }, audience: { primary: "adults", ageRange: null, secondary: [] }, domains: ["wellness", "health"], emotionalGoals: ["dreamy", "calm"], requiredVisualSignals: ["midnight_sky", "soft_constellations"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["loto"], identityConflict: { structuralPattern: "community hub pattern with hero, about, services, schedule, pricing, testimonials, and contact", baselineIdentity: "reviewed loto baseline identity", requestedIdentity: "dreamy midnight sky and soft constellations" }, requiredVisualSignals: ["midnight_sky", "soft_constellations"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], structuralRationale: "Retains the hero, about, services, schedule, pricing, testimonials, and contact roles; practices, calendar, and membership require no role change." },
  {
    id: "prenatal-movement-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "wellness", language: "en", briefLength: "detailed",
    brief: "Inclusive prenatal/postnatal movement studio with instructors, schedule, memberships, FAQ, testimonials, and contact; identity: cheerful editorial color blocks",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "business", requiredSections: ["hero", "about", "services", "team", "pricing", "testimonials", "contact", "faq", "schedule"], primaryActions: ["memberships"], contentModel: "prenatal_postnatal_movement_studio" }, audience: { primary: "adults", ageRange: null, secondary: [] }, domains: ["wellness", "fitness"], emotionalGoals: ["cheerful", "inclusive"], requiredVisualSignals: ["editorial_color_blocks", "cheerful_color"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["poise"], identityConflict: { structuralPattern: "business pattern with hero, about, services, team, pricing, testimonials, contact, FAQ, and schedule", baselineIdentity: "reviewed poise baseline identity", requestedIdentity: "cheerful editorial color blocks" }, requiredVisualSignals: ["editorial_color_blocks", "cheerful_color"], forbiddenVisualSignals: ["gaming_esports", "corporate_dashboard"], structuralRationale: "Retains the hero, about, services, team, pricing, testimonials, contact, FAQ, and schedule roles; instructors, memberships, and schedule require no role change." },
  {
    id: "retro-cli-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "technical_saas", language: "es", briefLength: "short",
    brief: "Documentación de una CLI para equipos de desarrollo; identity: retro technical manual with orange ink, not a terminal clone",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "documentation_site", requiredSections: ["hero", "features", "how_it_works", "testimonials", "pricing", "faq", "footer"], primaryActions: ["documentation"], contentModel: "cli_documentation" }, audience: { primary: "developers", ageRange: null, secondary: [] }, domains: ["developer_tools", "software_development"], emotionalGoals: ["technical", "distinctive"], requiredVisualSignals: ["retro_technical_manual", "orange_ink"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], explicitConstraints: ["not a terminal clone"], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["codex"], identityConflict: { structuralPattern: "documentation site pattern with hero, features, how-it-works, testimonials, pricing, FAQ, and footer", baselineIdentity: "reviewed codex baseline identity", requestedIdentity: "retro technical manual with orange ink, not a terminal clone" }, requiredVisualSignals: ["retro_technical_manual", "orange_ink"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], structuralRationale: "Retains the hero, features, how-it-works, testimonials, pricing, FAQ, and footer roles; CLI documentation requires no role change." },
  {
    id: "component-cloud-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "technical_saas", language: "en", briefLength: "medium",
    brief: "SaaS component delivery platform with workflow, features, pricing, social proof, FAQ, and CTA; identity: expressive modular shapes and electric lime",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "saas_product_page", requiredSections: ["hero", "features", "how_it_works", "pricing", "testimonials", "faq", "call_to_action", "footer"], primaryActions: ["call_to_action"], contentModel: "component_delivery_platform" }, audience: { primary: "developers", ageRange: null, secondary: [] }, domains: ["developer_tools", "saas"], emotionalGoals: ["expressive", "energetic"], requiredVisualSignals: ["modular_shapes", "electric_lime"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["pavilion"], identityConflict: { structuralPattern: "SaaS product page pattern with hero, features, how-it-works, pricing, testimonials, FAQ, CTA, and footer", baselineIdentity: "reviewed pavilion baseline identity", requestedIdentity: "expressive modular shapes and electric lime" }, requiredVisualSignals: ["modular_shapes", "electric_lime"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], structuralRationale: "Retains the hero, features, how-it-works, pricing, testimonials, FAQ, CTA, and footer roles; component delivery workflow requires no role change." },
  {
    id: "open-source-observability-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "technical_saas", language: "es", briefLength: "detailed",
    brief: "Open-source observability product landing page with capabilities, workflow, proof, and contribution CTA; identity: constructivist print system in red/cream/black",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "product_landing_page", requiredSections: ["hero", "features", "how_it_works", "testimonials", "call_to_action", "footer"], primaryActions: ["contribution"], contentModel: "open_source_observability_product" }, audience: { primary: "developers", ageRange: null, secondary: [] }, domains: ["developer_tools", "open_source"], emotionalGoals: ["bold", "technical"], requiredVisualSignals: ["constructivist_print", "red_cream_black"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["brasa"], identityConflict: { structuralPattern: "product landing page pattern with hero, features, how-it-works, testimonials, CTA, and footer", baselineIdentity: "reviewed brasa baseline identity", requestedIdentity: "constructivist print system in red, cream, and black" }, requiredVisualSignals: ["constructivist_print", "red_cream_black"], forbiddenVisualSignals: ["children_toy_ui", "wellness_organic"], structuralRationale: "Retains the hero, features, how-it-works, testimonials, CTA, and footer roles; capabilities, workflow, proof, and contribution require no role change." },
  {
    id: "color-photographer-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "editorial_portfolio", language: "es", briefLength: "short",
    brief: "Portafolio de fotógrafa cultural con proyectos, bio, testimonios y contacto; identity: saturated duotone and playful captions",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "portfolio", requiredSections: ["hero", "gallery", "about", "testimonials", "contact"], primaryActions: ["contact"], contentModel: "cultural_photographer_portfolio" }, audience: { primary: "creative_clients", ageRange: null, secondary: [] }, domains: ["portfolio", "photography"], emotionalGoals: ["playful", "saturated"], requiredVisualSignals: ["saturated_duotone", "playful_captions"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["margot-rey"], identityConflict: { structuralPattern: "portfolio pattern with hero, gallery, about, testimonials, and contact", baselineIdentity: "reviewed margot-rey baseline identity", requestedIdentity: "saturated duotone and playful captions" }, requiredVisualSignals: ["saturated_duotone", "playful_captions"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], structuralRationale: "Retains the hero, gallery, about, testimonials, and contact roles; cultural projects and biography require no role change." },
  {
    id: "literary-newsletter-en", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "editorial_portfolio", language: "en", briefLength: "medium",
    brief: "Literary newsletter/blog with issue list, membership CTA, author header, and footer; identity: maximal collage and marginalia",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "en", functional: { siteType: "blog", requiredSections: ["header", "call_to_action", "content_list", "footer"], primaryActions: ["membership"], contentModel: "literary_newsletter_blog" }, audience: { primary: "readers", ageRange: null, secondary: [] }, domains: ["editorial", "publishing"], emotionalGoals: ["literary", "maximal"], requiredVisualSignals: ["maximal_collage", "marginalia"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["inkwell"], identityConflict: { structuralPattern: "blog pattern with header, CTA, content list, and footer", baselineIdentity: "reviewed inkwell baseline identity", requestedIdentity: "maximal collage and marginalia" }, requiredVisualSignals: ["maximal_collage", "marginalia"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], structuralRationale: "Retains the header, CTA, content list, and footer roles; issue list, membership, and author header require no role change." },
  {
    id: "friendly-design-portfolio-es", datasetVersion: VISUAL_ENGINE_2A_DATASET_VERSION, archetype: "editorial_portfolio", language: "es", briefLength: "detailed",
    brief: "Portfolio de estudio de diseño con presentación, enfoque, clientes y contacto; identity: handmade shapes, warm color, approachable voice",
    expectedIntent: { schemaVersion: "intent-analysis/1.0", language: "es", functional: { siteType: "portfolio", requiredSections: ["hero", "about", "clients", "contact"], primaryActions: ["contact"], contentModel: "design_studio_portfolio" }, audience: { primary: "creative_clients", ageRange: null, secondary: [] }, domains: ["portfolio", "illustration"], emotionalGoals: ["warm", "approachable"], requiredVisualSignals: ["handmade_shapes", "warm_color", "approachable_voice"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], explicitConstraints: [], ambiguities: [], confidence: 0.95 },
    allowedSkeletonTemplateIds: ["marquee"], identityConflict: { structuralPattern: "portfolio pattern with hero, about, clients, and contact", baselineIdentity: "reviewed marquee baseline identity", requestedIdentity: "handmade shapes, warm color, approachable voice" }, requiredVisualSignals: ["handmade_shapes", "warm_color", "approachable_voice"], forbiddenVisualSignals: ["saas_dashboard", "course_progress_ui"], structuralRationale: "Retains the hero, about, clients, and contact roles; studio presentation, approach, clients, and contact require no role change." },
] as const;

export const VISUAL_ENGINE_2A_PILOT_CASES: readonly VisualEngine2APilotCase[] = deepFreeze(
  VisualEngine2APilotCaseSchema.array().length(15).parse(COHORT_ROWS),
);
