// Pre-bake Lucide icon SVG strings to a static module.
//
// We can't call renderToStaticMarkup from inside the Next.js bundle — server
// components aren't allowed to import "react-dom/server" (build error). So we
// generate the map once here, in a Node script, and commit the output. The
// runtime (lib/lucide-svg.ts) then just reads strings.
//
// Re-run after editing CURATED_ICONS:  npm run bake:lucide

import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { writeFileSync } from "fs";
import { CURATED_ICONS } from "../lib/lucide-curated";

const OUT = "lib/lucide-svgs.generated.ts";

const entries: string[] = [];
for (const { name, Component } of CURATED_ICONS) {
  const el = createElement(Component, {
    width: "1em",
    height: "1em",
    strokeWidth: 2,
    "aria-hidden": "true",
    focusable: "false",
  });
  const svg = renderToStaticMarkup(el);
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`);
}

const file = `// AUTO-GENERATED by scripts/bake-lucide-svgs.ts. Do not edit by hand.
// Re-run with: npm run bake:lucide

export const LUCIDE_SVGS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT, file, "utf8");
process.stdout.write(`Wrote ${OUT} (${entries.length} icons)\n`);
