import { config as loadEnv } from "dotenv";
loadEnv({ path: ".env.local" });

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { applyOps, parseOps, stripOpIds, tagWithOpIds } from "../lib/html-ops";

const TOGETHER_ENDPOINT = "https://api.together.xyz/v1/chat/completions";
const MODEL_ID = "moonshotai/Kimi-K2.6";
const MAX_TOKENS = 16_000;
const TEMPERATURE = 0.6;

// Sample business data for the smoke test. Two flavors: a SaaS that aligns
// naturally with the Mirror template, and a Latam taquería that stresses the
// structural mismatch (template was built for B2B SaaS, business is restaurant).
const SAMPLES = {
  saas: {
    label: "Stencil (Latam SaaS)",
    locale: "es-MX",
    data: {
      business_name: "Stencil",
      industry: "AI landing page builder for indie hackers",
      tagline_es: "Páginas de aterrizaje hermosas, generadas con AI en 30 segundos",
      tagline_en: "Beautiful landing pages, generated by AI in 30 seconds",
      pitch: "Stencil te da una página completa lista para vender, con un solo prompt. Desplegada a tu propio subdominio en 1 click.",
      hero_keyword: "vender",
      features: [
        {
          title: "Generación AI con un solo prompt",
          desc: "Describí tu negocio en 2 frases. Kimi K2.6 te entrega una página completa con copy, layout y diseño en menos de 30 segundos.",
        },
        {
          title: "50 templates curados a mano",
          desc: "Cada template fue diseñado en Claude Opus 4.7. No usás generadores genéricos — picás de una galería estilo Linear, Stripe, Anthropic.",
        },
        {
          title: "Deploy a tu subdominio en 1 click",
          desc: "Tu página vive en tu-marca.openlen.com. Sin configurar DNS, sin tarjeta de crédito para empezar.",
        },
        {
          title: "Historial de versiones automático",
          desc: "Cada cambio que el AI hace queda guardado. Si no te convence, volvés a la versión anterior en un click.",
        },
      ],
      pricing: [
        { name: "Free", price: "$0", period: "/mes", features: ["3 páginas", "Subdominio openlen.com", "Versiones automáticas"] },
        { name: "Pro", price: "$9", period: "/mes", features: ["Páginas ilimitadas", "Dominio propio", "AI ilimitado", "Sin marca OpenLen"] },
        { name: "Team", price: "$29", period: "/mes", features: ["5 asientos", "Colaboración", "Roles y permisos", "Soporte prioritario"] },
      ],
      testimonials: [
        { name: "Mariana Rojas", role: "Fundadora", company: "Frubana", quote: "Hice mi landing en 4 minutos. Antes me tomaba 2 días con Framer." },
        { name: "Carlos Hernández", role: "Indie hacker", company: "Cobertura", quote: "Es el primer constructor donde NO termino editando cada pixel a mano. El AI me deja casi lista." },
        { name: "Sofía Mendoza", role: "Marketing Lead", company: "Bitso", quote: "Probé v0, Lovable, Bolt. Para landing pages no-técnicas en español, OpenLen le pasa por encima a todos." },
      ],
      cta_primary: "Empezar gratis",
      cta_secondary: "Ver templates",
      faq_questions: [
        { q: "¿Necesito saber programar?", a: "No. El AI hace todo. Vos sólo describís tu negocio y editás copy si querés." },
        { q: "¿En qué idiomas funciona?", a: "Español y inglés nativos. El AI detecta el idioma de tu input y genera en ese mismo." },
        { q: "¿Puedo usar mi propio dominio?", a: "Sí, en el plan Pro. Te ayudamos a configurarlo en 5 minutos." },
        { q: "¿Mis datos están seguros?", a: "Sí. Hosteado en Hetzner (Alemania), datos cifrados, cumple GDPR." },
      ],
    },
  },
  taqueria: {
    label: "Tacos de Juan (Latam restaurant)",
    locale: "es-MX",
    data: {
      business_name: "Tacos de Juan",
      industry: "Taquería tradicional mexicana",
      tagline_es: "Auténticos tacos al pastor desde 1989",
      pitch: "Más de 30 años sirviendo los mejores tacos al pastor de Monterrey. Tradición familiar, ingredientes frescos, salsa hecha en casa.",
      hero_keyword: "tradición",
      features: [
        {
          title: "Al pastor sobre trompo",
          desc: "Carne marinada por 24 horas, cocinada lento sobre el trompo tradicional. La misma receta de mi abuelo Juan desde 1989.",
        },
        {
          title: "Salsa hecha en casa",
          desc: "Roja, verde, habanera y de mango. Todas hechas a mano cada mañana con chiles tostados en comal.",
        },
        {
          title: "Tortillas recién hechas",
          desc: "Maíz nixtamalizado, masa fresca, cocidas al momento. Nunca de bolsa.",
        },
        {
          title: "Servicio rápido a domicilio",
          desc: "Pide por WhatsApp y te llega caliente en 25 minutos. Cobertura toda la zona centro de Monterrey.",
        },
      ],
      pricing: [
        { name: "Taco al pastor", price: "$25", period: "/pieza", features: ["Servido con cebolla", "Cilantro fresco", "Salsa a elegir"] },
        { name: "Orden de 5", price: "$110", period: "", features: ["Mezcla a tu gusto", "Incluye refresco", "Incluye salsa extra"] },
        { name: "Familiar (12 tacos)", price: "$250", period: "", features: ["Para 4 personas", "2 refrescos grandes", "Postre incluido"] },
      ],
      testimonials: [
        { name: "María González", role: "Vecina del centro", company: "Cliente desde 2003", quote: "Llevo 20 años viniendo cada viernes. Es de los pocos lugares donde el sabor no ha cambiado." },
        { name: "Luis Martínez", role: "Chef", company: "Restaurante Pangea", quote: "Como chef puedo decir que la marinada del al pastor es ejemplar. Equilibrio perfecto." },
        { name: "Ana Torres", role: "Madre de familia", company: "Vecina", quote: "Pedimos cada domingo en familia. A los niños les encanta el sabor de la salsa de mango." },
      ],
      cta_primary: "Pide por WhatsApp",
      cta_secondary: "Ver el menú",
      faq_questions: [
        { q: "¿Hacen entregas a domicilio?", a: "Sí, en zona centro de Monterrey, pedido mínimo $150. Tiempo promedio 25 minutos." },
        { q: "¿Tienen opciones sin carne?", a: "Sí, tenemos tacos de hongos al pastor y de papa con queso." },
        { q: "¿Cuáles son los horarios?", a: "Lunes a domingo, 6pm a 2am. Cocina cierra 30 min antes." },
        { q: "¿Aceptan tarjeta?", a: "Sí, todas las tarjetas y transferencia bancaria." },
      ],
    },
  },
} as const;

const SYSTEM_PROMPT = `You are filling a generic landing page template with a real business's specific data. Your job is to replace generic placeholder copy with the user's actual business details — surgically, at the leaf level. You do NOT redesign, restructure, or restyle the page.

═══════════════════════════════════════════
CRITICAL — TARGET DISCIPLINE (read this twice)
═══════════════════════════════════════════

You emit op="replace" ONLY on LEAF text-bearing elements:
  ✅ ALLOWED replace targets (tag must be one of):
     h1, h2, h3, h4, h5, h6, p, span, li, a, button, label, blockquote, em, strong, time, small, dt, dd, td, th, figcaption, summary

  ❌ FORBIDDEN replace targets (NEVER replace these — they contain children):
     html, head, body, main, section, header, footer, article, nav, aside, form, div, ul, ol, dl, table, tr, picture, figure

  Why: replacing a container DELETES all its children. The template has 600+ tagged elements, most of which are leaves nested inside containers. If you replace a container, every child id becomes invalid and every subsequent op fails.

For containers you want REMOVED (a whole section the business doesn't need), use:
  <edit op="delete" target="<container-id>" />

NEVER use op="replace" on a container. Either leave it alone or delete it.

═══════════════════════════════════════════
PROTOCOL — ID-tagged ops
═══════════════════════════════════════════

<edit op="replace" target="<id-of-LEAF-element>"><new>NEW HTML CONTENT for that leaf only</new></edit>
<edit op="delete" target="<id-of-container-or-leaf>" />

When you replace a leaf, the <new> content should be just the leaf element itself with new text inside. Example for an h1:
  GOOD: <edit op="replace" target="q"><new><h1 class="display mt-6">Tacos de Juan — Auténticos al pastor desde 1989</h1></new></edit>
  BAD:  <edit op="replace" target="0"><new><body>...whole body...</body></new></edit>  ← never replace body
  BAD:  <edit op="replace" target="q"><new><h1 data-op-id="q" class="display">...</h1></new></edit>  ← never include data-op-id

NEVER include data-op-id="..." in the HTML you emit. The server strips them; you don't need them.

═══════════════════════════════════════════
WHAT TO FILL — sparse-data discipline
═══════════════════════════════════════════

CORE RULE: **only replace template text with data the user actually provided.** If a user-data field is null, empty, or missing, LEAVE THE TEMPLATE'S ORIGINAL COPY IN PLACE — do NOT emit a replace op for that slot, and do NOT invent fictional copy.

Specifically:
- features array empty → don't touch feature sections; leave the template's generic feature copy intact
- pricing array empty → don't touch pricing sections
- testimonials array empty → don't touch testimonial sections
- faq_questions array empty → don't touch FAQ
- cta_secondary null → leave the secondary CTA's original text
- tagline_es / tagline_en null → don't replace the hero subheading

The user gets a partial fill (what they have data for) with the rest of the template untouched. THIS IS THE GOAL. Sparse data should result in FEWER ops, not more.

CTAs: replace ONLY if user provided cta_primary or cta_secondary. Don't translate or rewrite existing CTAs if the user didn't give you a replacement.

Match user's business data to contextually appropriate text slots:
- business_name → first wordmark / logo text in nav + footer
- tagline (es or en based on user's language) → hero subheading
- pitch → hero subheading paragraph (if there's one BELOW the h1)
- hero_keyword → spans a single word in the hero h1 with the template's accent class (look at the template's existing accent span pattern, reuse the same classes)
- features[] → feature card titles + descriptions, 1:1 mapping; if user has 4 features but template has 6 cards, only fill the first 4
- pricing[] → pricing tier names + prices + bullet lists; if user has 2 tiers but template has 3, delete the 3rd tier container via op="delete"
- testimonials[] → testimonial quotes + author lines; 1:1 mapping with cap at template count
- faq_questions[] → FAQ Q + A pairs; same 1:1 with cap

PRESERVE the LANGUAGE the user is using (Spanish vs English vs Portuguese, based on language_detected or which tagline field is filled). Do NOT translate the template's original copy that you DON'T replace.

For sections that semantically don't fit (e.g., "API documentation" on a restaurant template AND user data shows the user IS a restaurant): use op="delete" on the section container — but ONLY if user data clearly shows the mismatch. If user data is sparse, leave it alone.

═══════════════════════════════════════════
OUTPUT BUDGET
═══════════════════════════════════════════

- CAP at 64 ops total. Hard cap. If you go over, the request is rejected.
- The TYPICAL response is 20-50 ops: hero h1 + hero p + 3-4 feature titles + 3-4 feature descriptions + 3 pricing tier names + 3 prices + 9 pricing features (3×3) + 3 testimonial quotes + 3 testimonial authors + 4 FAQ Qs + 4 FAQ As + 2-3 CTAs = ~40 ops.
- Prioritize PROMINENCE: hero > main features > pricing > CTAs > testimonials > FAQ > footer. If you run out of budget, drop the less prominent.
- Use op="delete" SPARINGLY — only for sections that are truly inapplicable.

NEVER include data-slot-path anywhere (reserved editor marker).

═══════════════════════════════════════════
COPY LENGTH BUDGET — strict per element type
═══════════════════════════════════════════

The template was designed at certain font sizes for certain copy lengths. If you fill a 72px display heading with 60 chars of copy, it wraps to 3 lines and breaks the hero. Match the EXPECTED length per slot:

- HERO h1 (biggest heading on the page): 6-12 WORDS MAXIMUM. PUNCHY. If user data has a longer tagline, EXTRACT THE ESSENCE into a short version. Example:
  User tagline_es: "Páginas de aterrizaje hermosas, generadas con AI en 30 segundos"
  → Hero h1 must be: "Tu landing en 30 segundos" or "Páginas hechas por AI" (NOT the full tagline verbatim).
- HERO sub-paragraph (the <p> right under the h1): 15-25 words, ONE sentence. The longer user-provided "pitch" can go here.
- Section headings (h2/h3): 2-6 words. Topic-name level.
- Feature card titles (h3 inside cards): 2-5 words. "Generación AI" not "Generación AI con un solo prompt".
- Feature card descriptions (p inside cards): 15-30 words, 1-2 sentences max.
- Pricing tier names: 1-2 words ("Free", "Pro", "Team").
- Pricing tier features (bullet list items): 3-6 words each.
- Testimonial quotes: 1-2 sentences (15-30 words).
- Testimonial author lines: "Name · Role · Company" max.
- FAQ questions: 4-10 words, ending in "?".
- FAQ answers: 1-2 sentences.
- Button labels / CTAs: 1-4 words ("Pide ahora", "Empezar gratis", "Ver demo").
- Footer copy: ultra-compact, label-style.

If user data has more detail than fits the slot, COMPRESS to the slot's budget. Don't try to fit everything verbatim — the template's design constrains the length.

═══════════════════════════════════════════
QUALITY BAR
═══════════════════════════════════════════

The output should read like the template was DESIGNED FOR this specific business — real numbers, real prices, real names, specific details. No Lorem Ipsum residue. No generic SaaS phrases like "Streamline your workflow" or "Built for the future". And NO truncation-prone long-form copy in slots designed for punchy text.

Output ONLY the <edits>...</edits> block. No preamble. No markdown fences. No commentary. Emit </edits> and nothing after.`;

function buildUserMessage(
  data: Record<string, unknown>,
  taggedHtml: string,
): string {
  return `Fill this landing page template with the business data below.

═══════════════════════════════════════════
BUSINESS DATA (JSON):
═══════════════════════════════════════════

${JSON.stringify(data, null, 2)}

═══════════════════════════════════════════
TEMPLATE HTML (every interesting element has a data-op-id attribute):
═══════════════════════════════════════════

${taggedHtml}

═══════════════════════════════════════════

Emit your <edits>...</edits> block now. Replace all generic copy with this business's actual data. Preserve the design 100% — only swap visible text. Match the business's language throughout. CAP at 64 ops.`;
}

async function callKimiStreaming(
  messages: { role: string; content: string }[],
): Promise<{ text: string; usage?: { prompt_tokens?: number; completion_tokens?: number }; finishReason: string | null }> {
  const apiKey = process.env.TOGETHER_API_KEY;
  if (!apiKey) throw new Error("TOGETHER_API_KEY not set");

  const res = await fetch(TOGETHER_ENDPOINT, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: MODEL_ID,
      messages,
      temperature: TEMPERATURE,
      max_tokens: MAX_TOKENS,
      stream: true,
      enable_thinking: false,
      chat_template_kwargs: { enable_thinking: false },
    }),
  });
  if (!res.ok || !res.body) {
    const body = await res.text().catch(() => "");
    throw new Error(`Together API ${res.status}: ${body.slice(0, 400)}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let sseBuf = "";
  let accumulated = "";
  let usage: { prompt_tokens?: number; completion_tokens?: number } | undefined;
  let finishReason: string | null = null;
  let progressCounter = 0;
  let lastLogged = Date.now();
  let upstreamDone = false;

  while (!upstreamDone) {
    const { done, value } = await reader.read();
    if (done) break;
    sseBuf += decoder.decode(value, { stream: true });
    let nl: number;
    while ((nl = sseBuf.indexOf("\n\n")) >= 0) {
      const block = sseBuf.slice(0, nl);
      sseBuf = sseBuf.slice(nl + 2);
      for (const line of block.split("\n")) {
        if (!line.startsWith("data: ")) continue;
        const payload = line.slice(6).trim();
        if (payload === "[DONE]") { upstreamDone = true; break; }
        try {
          const parsed = JSON.parse(payload) as {
            choices?: Array<{ delta?: { content?: string }; finish_reason?: string | null }>;
            usage?: { prompt_tokens?: number; completion_tokens?: number };
          };
          const chunk = parsed.choices?.[0]?.delta?.content ?? "";
          if (chunk) {
            accumulated += chunk;
            progressCounter += chunk.length;
            const now = Date.now();
            if (now - lastLogged > 2000) {
              process.stdout.write(`\r  streaming: ${(progressCounter / 1024).toFixed(1)} KB...    `);
              lastLogged = now;
            }
          }
          if (parsed.choices?.[0]?.finish_reason) finishReason = parsed.choices[0].finish_reason;
          if (parsed.usage) usage = parsed.usage;
        } catch { /* swallow */ }
      }
    }
  }
  process.stdout.write("\r" + " ".repeat(80) + "\r");
  return { text: accumulated, usage, finishReason };
}

async function main() {
  const args = process.argv.slice(2);
  let sampleId: keyof typeof SAMPLES | null = null;
  let templateName = "mirror";
  let fromJson: string | null = null;
  const positional: string[] = [];
  for (const a of args) {
    if (a.startsWith("--from-json=")) fromJson = a.slice(12);
    else positional.push(a);
  }
  if (fromJson) {
    templateName = positional[0] ?? "mirror";
  } else {
    sampleId = (positional[0] ?? "saas") as keyof typeof SAMPLES;
    templateName = positional[1] ?? "mirror";
  }

  let data: Record<string, unknown>;
  let label: string;
  if (fromJson) {
    if (!existsSync(fromJson)) {
      console.error(`JSON file not found: ${fromJson}`);
      process.exit(1);
    }
    data = JSON.parse(readFileSync(fromJson, "utf-8"));
    label = `extracted from ${fromJson}`;
  } else {
    if (!sampleId || !SAMPLES[sampleId]) {
      console.error(`Unknown sample '${sampleId}'. Choose: ${Object.keys(SAMPLES).join(" | ")} or use --from-json=<path>`);
      process.exit(1);
    }
    data = SAMPLES[sampleId].data as Record<string, unknown>;
    label = SAMPLES[sampleId].label;
  }

  const templatePath = join("public", "templates", "curated", `${templateName}.html`);
  if (!existsSync(templatePath)) {
    console.error(`Template not found: ${templatePath}`);
    process.exit(1);
  }

  console.log(`\n[test-fill] Filling ${templateName}.html with ${label}`);

  const sourceHtml = readFileSync(templatePath, "utf-8");
  const { taggedHtml, taggedCount } = tagWithOpIds(sourceHtml);
  console.log(`  source: ${(sourceHtml.length / 1024).toFixed(1)} KB`);
  console.log(`  tagged ${taggedCount} elements`);

  const messages = [
    { role: "system", content: SYSTEM_PROMPT },
    { role: "user", content: buildUserMessage(data, taggedHtml) },
  ];
  const promptSize = messages.reduce((acc, m) => acc + m.content.length, 0);
  console.log(`  prompt: ${(promptSize / 1024).toFixed(1)} KB`);

  console.log(`  calling Kimi K2.6 (enable_thinking: false, 16K max_tokens)...`);
  const t0 = Date.now();
  const { text: raw, usage, finishReason } = await callKimiStreaming(messages);
  const callMs = Date.now() - t0;
  console.log(`  Kimi returned in ${(callMs / 1000).toFixed(1)}s  (finish_reason=${finishReason ?? "?"})`);
  console.log(`  tokens: in=${usage?.prompt_tokens}, out=${usage?.completion_tokens}`);
  console.log(`  raw: ${(raw.length / 1024).toFixed(1)} KB`);

  const { ops, errors: parseErrors } = parseOps(raw);
  console.log(`  parsed ${ops.length} ops (${parseErrors.length} warnings)`);
  for (const e of parseErrors.slice(0, 3)) console.log(`    • ${e}`);

  if (ops.length === 0) {
    const dir = join(".style-match-test", "fill");
    mkdirSync(dir, { recursive: true });
    const slugFail = fromJson
      ? "from-" + (fromJson.split(/[/\\]/).pop() ?? "json").replace(/\.[^.]+$/, "")
      : sampleId ?? "sample";
    const dump = join(dir, `${templateName}-${slugFail}.raw.txt`);
    writeFileSync(dump, raw);
    console.log(`\n  ❌ No ops parsed. Raw saved: ${dump}`);
    process.exit(1);
  }

  const apply = applyOps(taggedHtml, ops);
  console.log(`  applied ${apply.appliedCount}/${ops.length} ops (${apply.errors.length} cascade warnings)`);
  for (const e of apply.errors.slice(0, 4)) {
    console.log(`    op ${e.opIndex} (${e.op} → ${e.target}): ${e.reason}`);
  }
  if (!apply.html) {
    const dir = join(".style-match-test", "fill");
    mkdirSync(dir, { recursive: true });
    const slugFail = fromJson
      ? "from-" + (fromJson.split(/[/\\]/).pop() ?? "json").replace(/\.[^.]+$/, "")
      : sampleId ?? "sample";
    writeFileSync(join(dir, `${templateName}-${slugFail}.raw.txt`), raw);
    console.log(`\n  ❌ Apply produced no HTML.`);
    process.exit(1);
  }
  const successRate = apply.appliedCount / ops.length;
  if (successRate < 0.8) {
    console.log(`\n  ⚠ Success rate ${(successRate * 100).toFixed(0)}% is below 80% threshold.`);
  } else {
    console.log(`  ✓ Success rate ${(successRate * 100).toFixed(0)}% — acceptable for autofill cascade.`);
  }

  const cleanHtml = stripOpIds(apply.html);
  const dir = join(".style-match-test", "fill");
  mkdirSync(dir, { recursive: true });
  const slug = fromJson
    ? "from-" + (fromJson.split(/[/\\]/).pop() ?? "json").replace(/\.[^.]+$/, "")
    : sampleId ?? "sample";
  const outPath = join(dir, `${templateName}-${slug}.html`);
  writeFileSync(outPath, cleanHtml);
  writeFileSync(join(dir, `${templateName}-${slug}.raw.txt`), raw);

  const fileUrl = (p: string) =>
    "file:///" + p.replace(/\\/g, "/").replace(/^([A-Z]):/, (_, d: string) => d.toLowerCase() + ":");
  console.log(`\n✓ Saved: ${outPath}`);
  console.log(`  Open: ${fileUrl(join(process.cwd(), outPath))}`);
  console.log(`  Original: ${fileUrl(join(process.cwd(), templatePath))}\n`);
}

main().catch((err) => {
  console.error("\nUnhandled:", err);
  process.exit(1);
});
