// @vitest-environment node
//
// /rest/v1 contra la LIBRERÍA REAL: `@supabase/supabase-js` 2.117.2 con su
// `fetch` apuntado a nuestro manejador, y la base del proyecto en PGlite
// (Postgres 18 de verdad). Lo que aquí pasa es lo que le pasará a la página que
// escriba Len: los mismos datos, los mismos errores, los mismos códigos.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { beforeAll, describe, expect, it } from "vitest";

import { handleBackendRequest, type BackendProject } from "../router";
import { CLUSTER_ROLES_SQL, initProjectDatabase } from "../schema";
import { newJwtSecret, newPublishableKey, newSecretKey, hashSecretKey } from "../keys";
import { asRole, newTestDatabase, pgliteProjectDatabase } from "../testing/pglite";

const REF = "abcdefghijklmnopqrst";
const DEV = `ol_${REF}`;
const URL_ = `https://${REF}.openlen.app`;

// Lo que Len escribiría en supabase/migrations/…_init.sql.
const MIGRACION = `
create table public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  precio numeric,
  activo boolean not null default true,
  tags text[] not null default '{}',
  datos jsonb,
  creado timestamptz not null default now()
);
alter table public.productos enable row level security;
create policy "todos leen" on public.productos for select using (true);
create policy "todos escriben" on public.productos for insert with check (true);
create policy "todos cambian" on public.productos for update using (true);
create policy "todos borran" on public.productos for delete using (true);

-- Un buzón: cualquiera deja un mensaje, nadie los lee (sin política de select).
create table public.buzon (id bigint generated always as identity primary key, texto text);
alter table public.buzon enable row level security;
create policy "dejar" on public.buzon for insert to anon with check (true);

-- Una tabla con RLS y sin políticas: cerrada.
create table public.secretos (id int primary key, valor text);
alter table public.secretos enable row level security;

create function public.suma(a int, b int) returns int language sql immutable as $$ select a + b $$;
create function public.baratos(maximo numeric) returns setof public.productos language sql stable as $$
  select * from public.productos where precio <= maximo order by precio
$$;
create function public.sin_nada() returns void language sql volatile as $$ select 1 $$;
`;

let supabase: SupabaseClient;
let project: BackendProject;
let secretKey: string;
const { pg, runner } = newTestDatabase();
const conClave = (key: string, extra: Record<string, unknown> = {}) =>
  createClient(URL_, key, {
    global: { fetch: (input, init) => handleBackendRequest(new Request(input, init), project) },
    auth: { persistSession: false, autoRefreshToken: false },
    ...extra,
  });

beforeAll(async () => {
  await runner.exec(CLUSTER_ROLES_SQL);
  await runner.exec(`create role ${DEV} nologin noinherit`);
  await initProjectDatabase(runner, { devRole: DEV });
  const r = await asRole(pg, DEV, null, (q) => q(MIGRACION));
  if (r && typeof r === "object" && "error" in r) throw new Error(String(r.error));

  const publishableKey = newPublishableKey();
  secretKey = newSecretKey();
  project = {
    ref: REF,
    publishableKey,
    secretKeyHash: hashSecretKey(secretKey),
    jwtSecret: newJwtSecret(),
    db: pgliteProjectDatabase(pg),
  };
  supabase = conClave(publishableKey);
  await runner.exec(`insert into public.secretos values (1, 'la receta')`);
});

describe("insert", () => {
  it("🔴 uno, con .select(): vuelve la fila con sus valores por defecto", async () => {
    const { data, error, status } = await supabase
      .from("productos")
      .insert({ nombre: "café", precio: 45.5, tags: ["bebida"], datos: { marca: "Oaxaca" } })
      .select()
      .single();
    expect(error).toBeNull();
    expect(status).toBe(201);
    expect(data).toMatchObject({ id: 1, nombre: "café", precio: 45.5, activo: true, tags: ["bebida"], datos: { marca: "Oaxaca" } });
    expect(data.creado).toMatch(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d+\+00:00$/);
  });

  it("varios a la vez con defaultToNull: false: lo que falta toma su DEFAULT", async () => {
    const { data, error } = await supabase
      .from("productos")
      .insert(
        [
          { nombre: "té", precio: 30 },
          { nombre: "pan", precio: 12, tags: ["comida", "dulce"] },
          { nombre: "agua" },
        ],
        { defaultToNull: false },
      )
      .select("id, nombre");
    expect(error).toBeNull();
    expect(data).toEqual([
      { id: 2, nombre: "té" },
      { id: 3, nombre: "pan" },
      { id: 4, nombre: "agua" },
    ]);
  });

  // (Va después del anterior: un insert que falla gasta un valor de la
  // secuencia `identity` —Postgres no lo devuelve— y correría los ids.)
  // Con claves distintas, supabase-js manda `columns=` con todas; lo que falta
  // es NULL explícito —como en Supabase—, salvo con `defaultToNull: false`
  // (`Prefer: missing=default`), que usa el DEFAULT de la columna.
  it("varios con claves distintas: lo que falta es NULL, y choca con un NOT NULL", async () => {
    const { error, status } = await supabase.from("productos").insert([{ nombre: "x1" }, { nombre: "x2", tags: ["a"] }]);
    expect(status).toBe(400);
    expect(error).toMatchObject({ code: "23502" });
  });

  it("🔴 sin .select() en una tabla sin política de lectura: entra igual (RETURNING 1, como PostgREST)", async () => {
    const { error, status, data } = await supabase.from("buzon").insert({ texto: "hola" });
    expect([error, status, data]).toEqual([null, 201, null]);
  });

  it("con .select() en esa tabla: el error de RLS de siempre", async () => {
    const { error, status } = await supabase.from("buzon").insert({ texto: "hola" }).select();
    expect(status).toBe(401);
    expect(error).toMatchObject({ code: "42501", message: 'new row violates row-level security policy for table "buzon"' });
  });

  it("un duplicado: 409 con el código de Postgres", async () => {
    const { error, status } = await supabase.from("productos").insert({ nombre: "café" });
    expect(status).toBe(409);
    expect(error).toMatchObject({ code: "23505", message: 'duplicate key value violates unique constraint "productos_nombre_key"' });
  });

  it("una columna que no existe: PGRST204", async () => {
    const { error, status } = await supabase.from("productos").insert({ nombre: "x", color: "rojo" });
    expect(status).toBe(400);
    expect(error).toMatchObject({ code: "PGRST204", message: "Could not find the 'color' column of 'productos' in the schema cache" });
  });
});

describe("select", () => {
  it("🔴 filtros, orden y límite", async () => {
    const { data, error } = await supabase
      .from("productos")
      .select("nombre, precio")
      .gte("precio", 12)
      .lt("precio", 46)
      .order("precio", { ascending: false })
      .limit(2);
    expect(error).toBeNull();
    expect(data).toEqual([
      { nombre: "café", precio: 45.5 },
      { nombre: "té", precio: 30 },
    ]);
  });

  it("ilike, in, is null, not, or", async () => {
    expect((await supabase.from("productos").select("nombre").ilike("nombre", "%A%").order("id")).data).toEqual([
      { nombre: "café" },
      { nombre: "pan" },
      { nombre: "agua" },
    ]);
    expect((await supabase.from("productos").select("nombre").in("nombre", ["pan", "agua", "nada"]).order("id")).data).toEqual([
      { nombre: "pan" },
      { nombre: "agua" },
    ]);
    expect((await supabase.from("productos").select("nombre").is("precio", null)).data).toEqual([{ nombre: "agua" }]);
    expect((await supabase.from("productos").select("nombre").not("precio", "is", null).order("id")).data).toHaveLength(3);
    expect((await supabase.from("productos").select("nombre").or("precio.lt.13,nombre.eq.té").order("id")).data).toEqual([
      { nombre: "té" },
      { nombre: "pan" },
    ]);
  });

  it("arrays y JSON: contains, ->>", async () => {
    expect((await supabase.from("productos").select("nombre").contains("tags", ["dulce"])).data).toEqual([{ nombre: "pan" }]);
    expect((await supabase.from("productos").select("nombre, marca:datos->>marca").eq("datos->>marca", "Oaxaca")).data).toEqual([
      { nombre: "café", marca: "Oaxaca" },
    ]);
    expect((await supabase.from("productos").select("datos->marca").eq("id", 1)).data).toEqual([{ marca: "Oaxaca" }]);
  });

  it("🔴 count exact con range: el total y un 206", async () => {
    const { data, count, status, error } = await supabase.from("productos").select("id", { count: "exact" }).order("id").range(0, 1);
    expect(error).toBeNull();
    expect([data, count, status]).toEqual([[{ id: 1 }, { id: 2 }], 4, 206]);
  });

  it("head con count: sólo el número", async () => {
    const { data, count, error } = await supabase.from("productos").select("*", { count: "exact", head: true });
    expect([data, count, error]).toEqual([null, 4, null]);
  });

  it("🔴 single y maybeSingle", async () => {
    expect((await supabase.from("productos").select("nombre").eq("id", 3).single()).data).toEqual({ nombre: "pan" });
    const none = await supabase.from("productos").select("nombre").eq("id", 999).single();
    expect(none.status).toBe(406);
    expect(none.error).toMatchObject({ code: "PGRST116", message: "Cannot coerce the result to a single JSON object", details: "The result contains 0 rows" });
    const maybe = await supabase.from("productos").select("nombre").eq("id", 999).maybeSingle();
    expect([maybe.data, maybe.error]).toEqual([null, null]);
  });

  it("una tabla con RLS y sin políticas: vacía, sin error", async () => {
    expect(await supabase.from("secretos").select("*")).toMatchObject({ data: [], error: null, status: 200 });
  });

  it("🔴 una tabla que no existe: PGRST205, 404", async () => {
    const { error, status } = await supabase.from("productoz").select("*");
    expect(status).toBe(404);
    expect(error).toMatchObject({
      code: "PGRST205",
      message: "Could not find the table 'public.productoz' in the schema cache",
      hint: "Perhaps you meant the table 'public.productos'",
    });
  });

  it("una columna que no existe: el 42703 de Postgres, 400", async () => {
    const { error, status } = await supabase.from("productos").select("colorr");
    expect(status).toBe(400);
    expect(error).toMatchObject({ code: "42703" });
  });

  it("un esquema que no se expone: PGRST106", async () => {
    const { error, status } = await supabase.schema("auth").from("users").select("*");
    expect(status).toBe(406);
    expect(error).toMatchObject({ code: "PGRST106", message: "Invalid schema: auth", hint: "Only the following schemas are exposed: public" });
  });

  it("csv", async () => {
    const { data } = await supabase.from("productos").select("id,nombre").lte("id", 2).order("id").csv();
    expect(data).toBe('id,nombre\n1,café\n2,té');
  });
});

describe("update, upsert, delete", () => {
  it("🔴 update con filtro y .select()", async () => {
    const { data, error, status } = await supabase.from("productos").update({ precio: 50 }).eq("nombre", "café").select("nombre, precio");
    expect([error, status]).toEqual([null, 200]);
    expect(data).toEqual([{ nombre: "café", precio: 50 }]);
  });

  it("update sin .select(): 204", async () => {
    const { error, status, data } = await supabase.from("productos").update({ activo: false }).eq("nombre", "agua");
    expect([error, status, data]).toEqual([null, 204, null]);
  });

  it("🔴 upsert por la columna única: actualiza el que hay y crea el que falta", async () => {
    const { data, error } = await supabase
      .from("productos")
      .upsert(
        [
          { nombre: "té", precio: 33 },
          { nombre: "jugo", precio: 25 },
        ],
        { onConflict: "nombre" },
      )
      .select("nombre, precio")
      .order("nombre");
    expect(error).toBeNull();
    expect(data).toEqual([
      { nombre: "jugo", precio: 25 },
      { nombre: "té", precio: 33 },
    ]);
    expect((await supabase.from("productos").select("id", { count: "exact", head: true })).count).toBe(5);
  });

  it("upsert ignorando duplicados", async () => {
    const { data, error } = await supabase.from("productos").upsert({ nombre: "té", precio: 1 }, { onConflict: "nombre", ignoreDuplicates: true }).select();
    expect([data, error]).toEqual([[], null]);
  });

  it("🔴 delete con filtro", async () => {
    const { error, status } = await supabase.from("productos").delete().eq("nombre", "jugo");
    expect([error, status]).toEqual([null, 204]);
    const borrado = await supabase.from("productos").delete().eq("nombre", "agua").select("nombre");
    expect(borrado.data).toEqual([{ nombre: "agua" }]);
    expect((await supabase.from("productos").select("id", { count: "exact", head: true })).count).toBe(3);
  });
});

describe("rpc", () => {
  it("🔴 una función escalar", async () => {
    expect(await supabase.rpc("suma", { a: 2, b: 3 })).toMatchObject({ data: 5, error: null, status: 200 });
  });

  it("una que devuelve filas, con filtros y orden encima", async () => {
    const { data, error } = await supabase.rpc("baratos", { maximo: 40 }).select("nombre");
    expect(error).toBeNull();
    expect(data).toEqual([{ nombre: "pan" }, { nombre: "té" }]);
  });

  it("void: 204 y data null", async () => {
    expect(await supabase.rpc("sin_nada")).toMatchObject({ data: null, error: null, status: 204 });
  });

  it("una que no existe: PGRST202", async () => {
    const { error, status } = await supabase.rpc("resta", { a: 1 });
    expect(status).toBe(404);
    expect(error).toMatchObject({ code: "PGRST202", message: "Could not find the function public.resta(a) in the schema cache" });
  });
});

describe("las reglas de Supabase que no son de PostgREST", () => {
  // pg-safeupdate: Supabase lo carga, y PostgREST lo devuelve como 400.
  it("🔴 delete y update sin filtro: «requires a WHERE clause»", async () => {
    const d = await supabase.from("productos").delete();
    expect(d.status).toBe(400);
    expect(d.error).toMatchObject({ code: "21000", message: "DELETE requires a WHERE clause" });
    const u = await supabase.from("productos").update({ activo: true });
    expect(u.error).toMatchObject({ code: "21000", message: "UPDATE requires a WHERE clause" });
    expect((await supabase.from("productos").select("id", { count: "exact", head: true })).count).toBe(3);
  });
});

describe("la puerta: claves y JWT", () => {
  it("🔴 una clave que no es la del proyecto: 401 «Invalid API key»", async () => {
    const r = await conClave(newPublishableKey()).from("productos").select("*");
    expect(r.status).toBe(401);
    expect(r.error).toMatchObject({ message: "Invalid API key" });
  });

  it("sin clave: 401 «No API key found in request»", async () => {
    const res = await handleBackendRequest(new Request(`${URL_}/rest/v1/productos`), project);
    expect(res.status).toBe(401);
    expect(await res.json()).toEqual({ message: "No API key found in request", hint: "No `apikey` request header or url param was found." });
  });

  it("🔴 un JWT firmado con otro secreto: 401 PGRST301, y no se lee nada", async () => {
    const { signJwt } = await import("../keys");
    const falso = await signJwt(newJwtSecret(), { sub: "x", role: "service_role" }, 3600);
    const r = await conClave(project.publishableKey, { global: { headers: { Authorization: `Bearer ${falso}` }, fetch: (i: RequestInfo | URL, init?: RequestInit) => handleBackendRequest(new Request(i, init), project) } })
      .from("secretos")
      .select("*");
    expect(r.status).toBe(401);
    expect(r.error).toMatchObject({ code: "PGRST301" });
  });

  it("BRAZO DE CONTROL: con la clave secreta (service_role) RLS no aplica y se ve lo cerrado", async () => {
    expect((await supabase.from("secretos").select("valor")).data).toEqual([]);
    expect((await conClave(secretKey).from("secretos").select("valor")).data).toEqual([{ valor: "la receta" }]);
  });

  it("CORS: el preflight responde y Content-Range se deja leer", async () => {
    const pre = await handleBackendRequest(
      new Request(`${URL_}/rest/v1/productos`, { method: "OPTIONS", headers: { origin: "https://tienda.openlen.app", "access-control-request-headers": "apikey,authorization" } }),
      project,
    );
    expect(pre.status).toBe(200);
    expect(pre.headers.get("access-control-allow-origin")).toBe("https://tienda.openlen.app");
    const res = await handleBackendRequest(
      new Request(`${URL_}/rest/v1/productos?select=id`, { headers: { apikey: project.publishableKey, origin: "https://tienda.openlen.app" } }),
      project,
    );
    expect(res.headers.get("access-control-expose-headers")).toContain("Content-Range");
  });
});
