// One-shot: give the 61 premium template images (single-size on R2) proper
// 400/800 WebP variants so the "Imagenes by OpenLen" picker grid loads light
// thumbnails instead of full-size heroes.
//
// For each entry in PREMIUM_IMAGES it sources the original (local
// templates/starter/<t>-assets/<base>.webp, else fetches the live hero URL),
// resizes via the shared image pipeline, uploads <t>/<base>-{800,400}.webp to
// R2, then rewrites premium-meta.ts + manifest.json so tablet→800, thumb→400
// (hero stays the full original). Idempotent — safe to re-run.
//
// Egress is blocked in Claude's sandbox, so RUN THIS IN YOUR TERMINAL (R2 creds
// in .env.local):  npm run openlen-images:premium-variants
// Then commit premium-meta.ts + manifest.json and `npm run deploy:prod`.

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { processImage } from "../../lib/images";
import { getOpenLenImageStorage } from "../../lib/storage/openlen-images";
import { PREMIUM_IMAGES, type PremiumImage } from "./premium-meta";

const ASSETS_DIR = "templates/starter";
const MANIFEST = join("public", "openlen-images", "manifest.json");
const META_TS = join("scripts", "openlen-images", "premium-meta.ts");

function parseHero(url: string): { t: string; base: string } | null {
  const m = url.match(/images\.openlen\.com\/([^/]+)\/(.+)\.webp$/);
  return m ? { t: m[1], base: m[2] } : null;
}

async function sourceBytes(t: string, base: string, heroUrl: string): Promise<Buffer> {
  const local = join(ASSETS_DIR, `${t}-assets`, `${base}.webp`);
  if (existsSync(local)) return readFile(local);
  // No local copy — pull the live original off R2 (needs egress).
  const res = await fetch(heroUrl);
  if (!res.ok) throw new Error(`no local source + fetch ${heroUrl} → ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

function renderMetaTs(images: PremiumImage[]): string {
  return `// AUTO-GENERATED — premium template imagery for the "Imagenes by OpenLen" picker.
// These images live on R2 (images.openlen.com/<template>/...). hero = full original;
// tablet = -800.webp, thumb = -400.webp (generated by premium-variants.ts). process.ts
// appends PREMIUM_IMAGES to the manifest on every regen so a reprocess never drops them.
import type { ImageStyle } from "./meta";
import type { TemplateFamily } from "../../lib/templates/families";

export interface PremiumImage {
  id: string;
  promptNum: number;
  style: ImageStyle;
  family: TemplateFamily[];
  alt: string;
  src: { hero: string; tablet: string; thumb: string };
}

export const PREMIUM_IMAGES: PremiumImage[] = ${JSON.stringify(images, null, 2)};
`;
}

async function main() {
  const usingR2 = !!(
    process.env.R2_ACCOUNT_ID &&
    process.env.R2_ACCESS_KEY &&
    process.env.R2_SECRET_KEY
  );
  if (!usingR2) {
    console.error(
      "No R2_* env vars — without them variants would write to the local FS\n" +
        "fallback (not R2), producing broken manifest URLs. Set R2 creds in\n" +
        ".env.local and re-run. Aborting.",
    );
    process.exit(1);
  }
  const storage = getOpenLenImageStorage();
  const updated: PremiumImage[] = [];
  let ok = 0;
  let kept = 0;

  for (const img of PREMIUM_IMAGES) {
    const parsed = parseHero(img.src.hero);
    if (!parsed) {
      console.warn(`skip (bad hero url): ${img.id}`);
      updated.push(img);
      kept++;
      continue;
    }
    const { t, base } = parsed;
    let bytes: Buffer;
    try {
      bytes = await sourceBytes(t, base, img.src.hero);
    } catch (e) {
      console.warn(`keep single-size — ${img.id}: ${(e as Error).message}`);
      updated.push(img);
      kept++;
      continue;
    }
    const { variants } = await processImage({
      input: bytes,
      variants: [
        { width: 800, format: "webp" as const, quality: 82 },
        { width: 400, format: "webp" as const, quality: 82 },
      ],
      autoOrient: false,
      withoutEnlargement: true,
    });
    const tablet = await storage.upload({
      key: `${t}/${base}-800.webp`,
      contentType: "image/webp",
      body: variants[0].bytes,
    });
    const thumb = await storage.upload({
      key: `${t}/${base}-400.webp`,
      contentType: "image/webp",
      body: variants[1].bytes,
    });
    updated.push({ ...img, src: { hero: img.src.hero, tablet: tablet.url, thumb: thumb.url } });
    ok++;
    console.log(`  ok  ${img.id}`);
  }

  await writeFile(META_TS, renderMetaTs(updated), "utf8");

  const mf = JSON.parse(await readFile(MANIFEST, "utf8")) as {
    version: number;
    generated: string;
    count: number;
    images: PremiumImage[];
  };
  const byId = new Map(updated.map((e) => [e.id, e]));
  mf.images = mf.images.map((i) => byId.get(i.id) ?? i);
  mf.count = mf.images.length;
  await writeFile(MANIFEST, JSON.stringify(mf, null, 2) + "\n", "utf8");

  console.log(
    `\nDone. ${ok} got 400/800 variants, ${kept} kept single-size. Manifest total: ${mf.count}.`,
  );
  console.log(`Now: commit ${META_TS} + ${MANIFEST}, then \`npm run deploy:prod\`.`);
}

main().catch((err) => {
  console.error(`\nFAILED: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
