// 20 OKLCH palette presets — generated by math from {brandHue, mode}.
// WCAG AA validation runs per palette; failures are surfaced for UI.
//
// Ported from claude.ai design-foundations artifact.

import { parseOklch, wcagContrast } from "../color";

export type PaletteMode = "light" | "dark";

export interface PaletteColors {
  bg: string;
  fg: string;
  fgMuted: string;
  fgDim: string;
  surface: string;
  surfaceElevated: string;
  border: string;
  borderStrong: string;
  accent: string;
  accentFg: string;
}

export interface PaletteSpec {
  id: string;
  name: string;
  brandHue: number;
  mode: PaletteMode;
  personality: string;
}

export interface ContrastCheck {
  name: string;
  ratio: number;
  min: number;
}

export interface PaletteValidation {
  checks: ContrastCheck[];
  ok: boolean;
}

export function generatePalette(brandHue: number, mode: PaletteMode): PaletteColors {
  if (mode === "light") {
    return {
      bg:              `oklch(98% 0.005 ${brandHue})`,
      fg:              `oklch(15% 0.01  ${brandHue})`,
      fgMuted:         `oklch(45% 0.01  ${brandHue})`,
      fgDim:           `oklch(60% 0.02  ${brandHue})`,
      surface:         `oklch(96% 0.008 ${brandHue})`,
      surfaceElevated: `oklch(94% 0.012 ${brandHue})`,
      border:          `oklch(85% 0.008 ${brandHue} / 0.6)`,
      borderStrong:    `oklch(70% 0.012 ${brandHue} / 0.8)`,
      accent:          `oklch(58% 0.22  ${brandHue})`,
      accentFg:        `oklch(98% 0.005 ${brandHue})`,
    };
  }
  return {
    bg:              `oklch(11% 0.01  ${brandHue})`,
    fg:              `oklch(95% 0.005 ${brandHue})`,
    fgMuted:         `oklch(70% 0.012 ${brandHue})`,
    fgDim:           `oklch(55% 0.01  ${brandHue})`,
    surface:         `oklch(15% 0.015 ${brandHue})`,
    surfaceElevated: `oklch(18% 0.018 ${brandHue})`,
    border:          `oklch(25% 0.012 ${brandHue} / 0.6)`,
    borderStrong:    `oklch(40% 0.015 ${brandHue} / 0.8)`,
    accent:          `oklch(68% 0.22  ${brandHue})`,
    accentFg:        `oklch(15% 0.01  ${brandHue})`,
  };
}

export const PALETTE_PRESETS: PaletteSpec[] = [
  { id: "coral-editorial",  name: "Coral Editorial",  brandHue: 12,  mode: "light", personality: "warm, editorial"    },
  { id: "coral-midnight",   name: "Coral Midnight",   brandHue: 12,  mode: "dark",  personality: "bold, premium"      },
  { id: "indigo-classic",   name: "Indigo Classic",   brandHue: 245, mode: "light", personality: "technical, calm"    },
  { id: "indigo-slate",     name: "Indigo Slate",     brandHue: 245, mode: "dark",  personality: "Linear / Vercel"    },
  { id: "emerald-fresh",    name: "Emerald Fresh",    brandHue: 145, mode: "light", personality: "clean, hopeful"     },
  { id: "emerald-forest",   name: "Emerald Forest",   brandHue: 145, mode: "dark",  personality: "grounded, trust"    },
  { id: "violet-editorial", name: "Violet Editorial", brandHue: 285, mode: "light", personality: "refined, creative"  },
  { id: "violet-night",     name: "Violet Night",     brandHue: 285, mode: "dark",  personality: "luxury, late-night" },
  { id: "amber-warm",       name: "Amber Warm",       brandHue: 38,  mode: "light", personality: "inviting, sunset"   },
  { id: "amber-espresso",   name: "Amber Espresso",   brandHue: 38,  mode: "dark",  personality: "warm, intimate"     },
  { id: "rose-light",       name: "Rose Light",       brandHue: 350, mode: "light", personality: "playful, soft"      },
  { id: "rose-dusk",        name: "Rose Dusk",        brandHue: 350, mode: "dark",  personality: "sultry, romantic"   },
  { id: "cyan-crisp",       name: "Cyan Crisp",       brandHue: 195, mode: "light", personality: "modern, devtool"    },
  { id: "cyan-deep",        name: "Cyan Deep",        brandHue: 195, mode: "dark",  personality: "aquatic, calm"      },
  { id: "lime-pop",         name: "Lime Pop",         brandHue: 90,  mode: "light", personality: "energetic, young"   },
  { id: "lime-vintage",     name: "Lime Vintage",     brandHue: 90,  mode: "dark",  personality: "retro, terminal"    },
  { id: "slate-mono",       name: "Slate Mono",       brandHue: 220, mode: "light", personality: "neutral, business"  },
  { id: "carbon-mono",      name: "Carbon Mono",      brandHue: 220, mode: "dark",  personality: "premium tech"       },
  { id: "magenta-vivid",    name: "Magenta Vivid",    brandHue: 320, mode: "light", personality: "bold, fashion"      },
  { id: "magenta-vinyl",    name: "Magenta Vinyl",    brandHue: 320, mode: "dark",  personality: "club, music"        },
];

export function validatePalette(p: PaletteColors): PaletteValidation {
  const bg = parseOklch(p.bg);
  const fg = parseOklch(p.fg);
  const accent = parseOklch(p.accent);
  const accentFg = parseOklch(p.accentFg);
  if (!bg || !fg || !accent || !accentFg) {
    return { checks: [], ok: false };
  }
  const checks: ContrastCheck[] = [
    { name: "bg/fg",           ratio: wcagContrast(bg, fg),            min: 4.5 },
    { name: "accent/bg",       ratio: wcagContrast(accent, bg),        min: 3.0 },
    { name: "accent/accentFg", ratio: wcagContrast(accent, accentFg),  min: 4.5 },
  ];
  const fails = checks.filter(c => c.ratio < c.min);
  return { checks, ok: fails.length === 0 };
}

// Lookup helper.
export function getPalette(id: string): PaletteSpec | undefined {
  return PALETTE_PRESETS.find(p => p.id === id);
}
